const express=require("express"),http=require("http"),{Server}=require("socket.io"),path=require("path");
const app=express(),srv=http.createServer(app),io=new Server(srv,{cors:{origin:"*"}});
const PORT=process.env.PORT||3000;
app.use(express.static(path.join(__dirname,"public")));
const rooms=new Map(),s2r=new Map(),CH="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
function mkC(){let c;do{c=Array.from({length:6},()=>CH[Math.floor(Math.random()*CH.length)]).join("")}while(rooms.has(c));return c}
function gT(r,iz){if(iz){const l=r<=2?3:r<=5?4:5,h2=r<=2?6:r<=5?8:12;return Math.round((l+Math.random()*(h2-l))*10)/10}const l=r<=2?1.5:r<=5?2:3,h2=r<=2?3.5:r<=5?6:9;return Math.round((l+Math.random()*(h2-l))*10)/10}
function pub(r){return{code:r.code,mode:r.mode,status:r.status,players:r.players.map(p=>({id:p.id,name:p.name,avatar:p.avatar,host:p.host,elim:p.elim})),round:r.round,totalRounds:r.totalRounds,target:r.mode==="zeit"?null:r.target,submitted:r.subs?Object.keys(r.subs).length:0,activeCount:r.players.filter(p=>!p.elim).length}}
function bc(c){const r=rooms.get(c);if(r)io.to(c).emit("state",pub(r))}
io.on("connection",sk=>{
sk.on("create",({name,avatar,mode,rounds},cb)=>{const c=mkC();const r={code:c,mode:mode||"normal",status:"lobby",players:[{id:sk.id,name,avatar,host:true,elim:false}],round:0,totalRounds:rounds||3,target:0,subs:{},finalTimes:{},roles:{},sabUsedGame:false,fakeResolved:false,sabResolved:false,votes:{},roundHistory:[]};rooms.set(c,r);sk.join(c);s2r.set(sk.id,c);cb({ok:true,code:c});bc(c)});
sk.on("join",({code:c,name,avatar},cb)=>{const r=rooms.get(c&&c.toUpperCase());if(!r)return cb({ok:false,err:"Room not found"});if(r.status!=="lobby")return cb({ok:false,err:"Game started"});if(r.players.length>=10)return cb({ok:false,err:"Room full"});r.players.push({id:sk.id,name,avatar,host:false,elim:false});sk.join(r.code);s2r.set(sk.id,r.code);cb({ok:true,code:r.code});bc(r.code)});
sk.on("start",()=>{const c=s2r.get(sk.id),r=rooms.get(c);if(!r)return;if(!r.players.find(x=>x.id===sk.id)?.host||r.players.length<2)return;r.status="playing";r.round=1;r.subs={};r.finalTimes={};r.target=gT(1,r.mode==="zeit");r.roundHistory=[];r.players.forEach(p=>p.elim=false);if(r.mode==="trust"){r.roles={};r.sabUsedGame=false;const ids=r.players.map(p=>p.id).sort(()=>Math.random()-.5);r.players.forEach(p=>r.roles[p.id]="normal");if(ids.length>=2){r.roles[ids[0]]="fake";r.roles[ids[1]]="saboteur"}r.players.forEach(p=>io.to(p.id).emit("role",{role:r.roles[p.id]}))}bc(c);io.to(c).emit("roundStart",{round:r.round,target:r.mode==="zeit"?null:r.target});if(r.mode==="zeit"){const rn=r.round;setTimeout(()=>{if(r.status==="playing"&&r.round===rn)io.to(c).emit("zeitStop")},r.target*1000+3000)}});
sk.on("submit",({time})=>{const c=s2r.get(sk.id),r=rooms.get(c);if(!r||r.status!=="playing")return;const p=r.players.find(x=>x.id===sk.id);if(!p||p.elim||r.subs[sk.id]!==undefined)return;r.subs[sk.id]=time;r.finalTimes[sk.id]=time;bc(c);if(Object.keys(r.subs).length>=r.players.filter(x=>!x.elim).length){if(r.mode==="trust"){r.status="hidden";r.fakeResolved=false;r.sabResolved=r.sabUsedGame;bc(c);const fi=Object.entries(r.roles).find(([,x])=>x==="fake"),si=Object.entries(r.roles).find(([,x])=>x==="saboteur");if(fi)io.to(fi[0]).emit("fakePrompt",{time:r.subs[fi[0]]});else r.fakeResolved=true;if(si&&!r.sabUsedGame)io.to(si[0]).emit("sabPrompt",{targets:r.players.filter(p2=>p2.id!==si[0]&&!p2.elim).map(p2=>({id:p2.id,name:p2.name}))});else r.sabResolved=true;setTimeout(()=>{if(r.status==="hidden")res(c)},12e3);chk(c)}else res(c)}});
sk.on("fakeAct",({dir})=>{const c=s2r.get(sk.id),r=rooms.get(c);if(!r||r.roles[sk.id]!=="fake"||r.fakeResolved)return;const o=r.subs[sk.id];if(o===undefined)return;r.finalTimes[sk.id]=o+(dir==="plus"?.4:-.4);r.fakeResolved=true;chk(c)});
sk.on("fakeSkip",()=>{const c=s2r.get(sk.id),r=rooms.get(c);if(!r||r.roles[sk.id]!=="fake")return;r.fakeResolved=true;chk(c)});
sk.on("sabAct",({targetId})=>{const c=s2r.get(sk.id),r=rooms.get(c);if(!r||r.roles[sk.id]!=="saboteur"||r.sabUsedGame)return;const tv=r.finalTimes[targetId];if(tv===undefined)return;r.finalTimes[targetId]=tv+((tv-r.target)>=0?.3:-.3);r.sabUsedGame=true;r.sabResolved=true;chk(c)});
sk.on("sabSkip",()=>{const c=s2r.get(sk.id),r=rooms.get(c);if(!r||r.roles[sk.id]!=="saboteur")return;r.sabResolved=true;chk(c)});
sk.on("vote",({fakeGuess,sabGuess})=>{const c=s2r.get(sk.id),r=rooms.get(c);if(!r||r.status!=="voting")return;r.votes[sk.id]={fake:fakeGuess,sab:sabGuess};if(Object.keys(r.votes).length>=r.players.length){const fi=Object.entries(r.roles).find(([,x])=>x==="fake"),si=Object.entries(r.roles).find(([,x])=>x==="saboteur");const fid=fi?fi[0]:null,sid=si?si[0]:null;const fV=Object.values(r.votes).filter(v=>v.fake===fid).length,sV=Object.values(r.votes).filter(v=>v.sab===sid).length,maj=Math.ceil(r.players.length/2);r.status="reveal";io.to(c).emit("tbReveal",{roles:r.roles,fakeId:fid,sabId:sid,fakeFound:fV>=maj,sabFound:sV>=maj,normalWin:fV>=maj&&sV>=maj,fV,sV,maj})}});
sk.on("nextRound",()=>{const c=s2r.get(sk.id),r=rooms.get(c);if(!r||!r.players.find(x=>x.id===sk.id)?.host)return;const act=r.players.filter(x=>!x.elim);if(r.mode==="trust"&&r.round>=r.totalRounds){r.status="voting";r.votes={};io.to(c).emit("voteStart",{players:r.players.map(p=>({id:p.id,name:p.name,avatar:p.avatar}))});return}if(act.length<=1||(r.mode!=="trust"&&r.round>=r.totalRounds)){end(c);return}r.round++;r.subs={};r.finalTimes={};r.target=gT(r.round,r.mode==="zeit");r.status="playing";r.fakeResolved=false;r.sabResolved=r.sabUsedGame;bc(c);io.to(c).emit("roundStart",{round:r.round,target:r.mode==="zeit"?null:r.target});if(r.mode==="zeit"){const rn=r.round;setTimeout(()=>{if(r.status==="playing"&&r.round===rn)io.to(c).emit("zeitStop")},r.target*1000+3000)}});
sk.on("disconnect",()=>{const c=s2r.get(sk.id);if(!c)return;const r=rooms.get(c);if(!r)return;r.players=r.players.filter(p=>p.id!==sk.id);if(!r.players.length)rooms.delete(c);else{if(!r.players.some(p=>p.host))r.players[0].host=true;bc(c)}s2r.delete(sk.id)});
});
function chk(c){const r=rooms.get(c);if(r&&r.status==="hidden"&&r.fakeResolved&&r.sabResolved)res(c)}
function res(c){const r=rooms.get(c);if(!r)return;const act=r.players.filter(p=>!p.elim),ft=r.finalTimes;const rs=act.map(p=>{const tv=ft[p.id]||r.subs[p.id]||0;return{id:p.id,name:p.name,avatar:p.avatar,time:Math.round(tv*1e3)/1e3,ms:Math.round(Math.abs(tv-r.target)*1e3),elim:false}}).sort((a,b)=>a.ms-b.ms);rs.forEach((x,i)=>x.rank=i+1);if(r.mode!=="trust"&&act.length>2){rs[rs.length-1].elim=true;const w=r.players.find(p=>p.id===rs[rs.length-1].id);if(w)w.elim=true}r.roundHistory.push({round:r.round,target:r.target,results:rs});r.status="results";io.to(c).emit("roundResults",{round:r.round,target:r.target,results:rs})}
function end(c){const r=rooms.get(c);if(!r)return;r.status="ended";io.to(c).emit("gameEnd",{winner:r.players.filter(p=>!p.elim)[0]?.name||"?"})}
app.get("/debug",(q,s)=>{const fs=require("fs");try{const files=fs.readdirSync(__dirname);const pubFiles=fs.existsSync(path.join(__dirname,"public"))?fs.readdirSync(path.join(__dirname,"public")):["NO public FOLDER"];s.json({dir:__dirname,files,pubFiles})}catch(e){s.json({error:e.message})}});
app.get("/",(q,s)=>s.sendFile(path.join(__dirname,"public","index.html")));
srv.listen(PORT,()=>console.log("TimeTap on :"+PORT));
