import { useState, useEffect, useRef, createContext, useContext } from "react";

/* ═══════ i18n ═══════ */
const L={de:{
sub:"Stoppe die Zeit. Triff die Zielzeit.",solo:"Solo",soloD:"Trainiere dein Timing",multi:"Multiplayer",multiD:"FFA · Team · Zeitgefühl",tb:"Trust Breaker",tbD:"Rollen · Täuschung · Drama",
settings:"Einstellungen",home:"Home",back:"Zurück",next:"Weiter",start:"Start",ready:"Bereit!",submit:"Abgeben",result:"Ergebnis",rnd:"Runde",rnds:"Runden",pts:"Punkte",dev:"Abweichung",tgt:"Ziel",tgtTime:"Zielzeit",
yourTime:"Deine Zeit",est:"Geschätzt",realT:"Echte Zeit",allRnds:"Alle Runden",winner:"Gewinner",winsTrn:"gewinnt das Turnier!",
perf:"PERFEKT!",strong:"Stark!",good:"Gut!",close:"Knapp",miss:"Daneben",
soloT:"Wie möchtest du spielen?",normal:"Normal",normalD:"Zielzeit sichtbar – stoppe zur richtigen Zeit",zeit:"Zeitgefühl",zeitD:"Kein Timer – schätze die Zeit im Kopf",
diff:"Schwierigkeit",rndCnt:"Rundenanzahl",howMany:"Wie viele Runden?",
easy:"Leicht",easyD:"Ganze Sekunden",med:"Mittel",medD:"1 Dezimalstelle",hard:"Schwer",hardD:"2 Dezimalstellen",
getReady:"Mach dich bereit",now:"JETZT!",countNow:"Ab jetzt zählen!",countAlong:"Zähle mit...",timerSince:'Timer läuft seit "JETZT!"',
stop:"STOP!",howLong:"Wie lange war das?",yourEst:"Deine Schätzung",overEst:"Überschätzt",underEst:"Unterschätzt",
howPlay:"Wie möchtest du spielen?",withWhom:"Mit wem spielst du?",
ffa:"Alle gegen alle",ffaD:"Turnier – einer fliegt raus",team:"Team gegen Team",teamD:"Kämpfe als Team um den Sieg",
tourn:"Ausscheidungsturnier",tournD:"Bis 10 Spieler · Schlechtester fliegt raus",
name:"Dein Name...",avatar:"Avatar wählen",create:"Erstellen",join:"Beitreten",joinRoom:"Raum beitreten",
roomCode:"Raum-Code",shareCode:"Teile diesen Code",copied:"Kopiert!",waitPl:"Warte auf Spieler...",waitHost:"Warte auf den Host...",
startGame:"Spiel starten",players:"Spieler",passPhone:"Gib das Handy an",tgtHidden:"Zielzeit ist versteckt",
elimRnd:"Eliminationsrunde",avgOver:"Durchschnitt über",subRnd:"Teilrunde",remaining:"übrig",isOut:"ist raus!",
teamTgt:"Team-Zielzeit",teamInfo:"Jeder stoppt einen Teil. Zeiten addiert. Näher am Ziel = Sieg!",
t1Start:"Team 1 startet",player:"Spieler",prevTime:"Bisherige Zeit",tgtWas:"Ziel war",won:"Gewonnen!",wins:"Siege",devMs:"Abw.",
tbTitle:"Trust Breaker",tb46:"4–6 Spieler · Rollen · Täuschung",rolesDistr:"Rollen werden verteilt...",whoFakeSab:"Wer ist Fake? Wer Saboteur?",
tapSee:"Antippen um Rolle zu sehen",role:"Deine Rolle",fake:"Fake",sab:"Saboteur",norm:"Normal",
fakeD:"±0.4s pro Runde",sabD:"1x sabotieren",normD:"Entlarve die Betrüger!",noShow:"Zeige niemandem deine Rolle!",
calc:"Berechne Ergebnis...",giveTo:"Gib an",yourTimeWas:"Deine Zeit",adjust:"Anpassen?",skip:"Skip",
alrUsed:"Bereits eingesetzt",sabotage:"Sabotiere",discuss:"Diskutiert frei – Host drückt weiter",voting:"Abstimmung",nextRnd:"Nächste Runde",
whoFake:"Wer ist Fake?",whoSab:"Wer ist Saboteur?",vote:"Abstimmen",reveal:"Aufdecken!",revealed:"Aufgedeckt!",
normWin:"Normale gewinnen!",cheatWin:"Betrüger gewinnen!",exposed:"enttarnt",undetected:"unentdeckt",votes:"Stimmen",
lang:"Sprache",theme:"Erscheinungsbild",dark:"Dunkel",light:"Hell",done:"Fertig",soloMode:"Solo Modus",
},en:{
sub:"Stop the time. Hit the target.",solo:"Solo",soloD:"Train your timing",multi:"Multiplayer",multiD:"FFA · Team · Time Feel",tb:"Trust Breaker",tbD:"Roles · Deception · Drama",
settings:"Settings",home:"Home",back:"Back",next:"Next",start:"Start",ready:"Ready!",submit:"Submit",result:"Result",rnd:"Round",rnds:"Rounds",pts:"Points",dev:"Deviation",tgt:"Target",tgtTime:"Target Time",
yourTime:"Your Time",est:"Estimated",realT:"Real Time",allRnds:"All Rounds",winner:"Winner",winsTrn:"wins the tournament!",
perf:"PERFECT!",strong:"Strong!",good:"Good!",close:"Close",miss:"Missed",
soloT:"How do you want to play?",normal:"Normal",normalD:"Target visible – stop at the right time",zeit:"Time Feel",zeitD:"No timer – estimate in your head",
diff:"Difficulty",rndCnt:"Rounds",howMany:"How many rounds?",
easy:"Easy",easyD:"Whole seconds",med:"Medium",medD:"1 decimal",hard:"Hard",hardD:"2 decimals",
getReady:"Get ready",now:"NOW!",countNow:"Start counting now!",countAlong:"Keep counting...",timerSince:'Timer since "NOW!"',
stop:"STOP!",howLong:"How long was that?",yourEst:"Your estimate",overEst:"Overestimated",underEst:"Underestimated",
howPlay:"How do you want to play?",withWhom:"Who are you playing with?",
ffa:"Free for All",ffaD:"Tournament – worst eliminated",team:"Team vs Team",teamD:"Fight as a team",
tourn:"Elimination Tournament",tournD:"Up to 10 players · Worst eliminated",
name:"Your name...",avatar:"Choose avatar",create:"Create",join:"Join",joinRoom:"Join Room",
roomCode:"Room Code",shareCode:"Share this code",copied:"Copied!",waitPl:"Waiting for players...",waitHost:"Waiting for host...",
startGame:"Start Game",players:"Players",passPhone:"Pass the phone to",tgtHidden:"Target time is hidden",
elimRnd:"Elimination Round",avgOver:"Average over",subRnd:"Sub-round",remaining:"remaining",isOut:"is out!",
teamTgt:"Team Target",teamInfo:"Each player stops part of the time. Times add up. Closest to target wins!",
t1Start:"Team 1 starts",player:"Player",prevTime:"Time so far",tgtWas:"Target was",won:"Won!",wins:"Wins",devMs:"Dev.",
tbTitle:"Trust Breaker",tb46:"4–6 players · Roles · Deception",rolesDistr:"Distributing roles...",whoFakeSab:"Who is Fake? Who is Saboteur?",
tapSee:"Tap to see your role",role:"Your Role",fake:"Fake",sab:"Saboteur",norm:"Normal",
fakeD:"±0.4s per round",sabD:"Sabotage once per game",normD:"Expose the cheaters!",noShow:"Don't show anyone!",
calc:"Calculating...",giveTo:"Pass to",yourTimeWas:"Your time",adjust:"Adjust?",skip:"Skip",
alrUsed:"Already used",sabotage:"Sabotage",discuss:"Discuss freely – host continues",voting:"Voting",nextRnd:"Next Round",
whoFake:"Who is the Fake?",whoSab:"Who is the Saboteur?",vote:"Vote",reveal:"Reveal!",revealed:"Revealed!",
normWin:"Normal players win!",cheatWin:"Cheaters win!",exposed:"exposed",undetected:"undetected",votes:"Votes",
lang:"Language",theme:"Appearance",dark:"Dark",light:"Light",done:"Done",soloMode:"Solo Mode",
},sq:{
sub:"Ndalo kohën. Qëllo objektivin.",solo:"Solo",soloD:"Stërvit kohën",multi:"Multiplayer",multiD:"FFA · Ekip · Ndjenja",tb:"Trust Breaker",tbD:"Role · Mashtrim · Dramë",
settings:"Cilësimet",home:"Kryefaqja",back:"Kthehu",next:"Vazhdo",start:"Fillo",ready:"Gati!",submit:"Dërgo",result:"Rezultati",rnd:"Raundi",rnds:"Raunde",pts:"Pikë",dev:"Devijimi",tgt:"Objektivi",tgtTime:"Koha objektiv",
yourTime:"Koha jote",est:"Vlerësuar",realT:"Koha reale",allRnds:"Të gjitha",winner:"Fituesi",winsTrn:"fiton turneun!",
perf:"PERFEKT!",strong:"Fortë!",good:"Mirë!",close:"Afër",miss:"Gabim",
soloT:"Si dëshiron të luash?",normal:"Normal",normalD:"Koha e dukshme – ndalo në kohë",zeit:"Ndjenja e Kohës",zeitD:"Pa kronometër – vlerëso në kokë",
diff:"Vështirësia",rndCnt:"Numri i raundeve",howMany:"Sa raunde?",
easy:"Lehtë",easyD:"Sekonda të plota",med:"Mesatare",medD:"1 shifër",hard:"Vështirë",hardD:"2 shifra",
getReady:"Përgatitu",now:"TANI!",countNow:"Fillo numërimin!",countAlong:"Vazhdo...",timerSince:'Kronometri nga "TANI!"',
stop:"NDALO!",howLong:"Sa kohë ishte?",yourEst:"Vlerësimi yt",overEst:"Mbivlerësuar",underEst:"Nënvlerësuar",
howPlay:"Si dëshiron të luash?",withWhom:"Me kë luan?",
ffa:"Të gjithë kundër",ffaD:"Turneu – më i keqi eliminohet",team:"Ekip kundër Ekipit",teamD:"Lufto si ekip",
tourn:"Turneu eliminues",tournD:"Deri 10 lojtarë · Më i keqi eliminohet",
name:"Emri yt...",avatar:"Zgjidh avatarin",create:"Krijo",join:"Bashkohu",joinRoom:"Bashkohu në dhomë",
roomCode:"Kodi",shareCode:"Ndaj kodin",copied:"Kopjuar!",waitPl:"Duke pritur...",waitHost:"Duke pritur hostin...",
startGame:"Fillo lojën",players:"Lojtarë",passPhone:"Jep telefonin",tgtHidden:"Koha e fshehur",
elimRnd:"Raundi eliminues",avgOver:"Mesatarja",subRnd:"Nën-raundi",remaining:"mbetur",isOut:"u eliminua!",
teamTgt:"Koha e ekipit",teamInfo:"Secili ndalon një pjesë. Kohët mblidhen. Më afër = fitore!",
t1Start:"Ekipi 1 fillon",player:"Lojtari",prevTime:"Deri tani",tgtWas:"Objektivi ishte",won:"Fitoi!",wins:"Fitore",devMs:"Dev.",
tbTitle:"Trust Breaker",tb46:"4–6 lojtarë · Role · Mashtrim",rolesDistr:"Rolet shpërndahen...",whoFakeSab:"Kush është Fake? Kush Saboteur?",
tapSee:"Prek për të parë",role:"Roli yt",fake:"Fake",sab:"Saboteur",norm:"Normal",
fakeD:"±0.4s për raund",sabD:"1x saboto dikë",normD:"Zbulo mashtruesit!",noShow:"Mos trego askujt!",
calc:"Duke llogaritur...",giveTo:"Jep te",yourTimeWas:"Koha jote",adjust:"Rregulloje?",skip:"Kalo",
alrUsed:"Tashmë përdorur",sabotage:"Saboto",discuss:"Diskutoni – hosti vazhdon",voting:"Votimi",nextRnd:"Raundi tjetër",
whoFake:"Kush është Fake?",whoSab:"Kush është Saboteur?",vote:"Voto",reveal:"Zbulo!",revealed:"U zbulua!",
normWin:"Normalët fituan!",cheatWin:"Mashtruesit fituan!",exposed:"zbuluar",undetected:"pazbuluar",votes:"Vota",
lang:"Gjuha",theme:"Pamja",dark:"Errët",light:"Ndriçuar",done:"Gati",soloMode:"Solo",
}};

/* ═══════ THEMES ═══════ */
const TH={dark:{bg:"#0B0B1E",card:"#141432",raised:"#1C1C42",tx:"#F1F0FF",sub:"#A5A3C8",mt:"#5D5B7A",ln:"#2D2D5E"},light:{bg:"#F5F3FF",card:"#FFFFFF",raised:"#EDE9FE",tx:"#1E1B4B",sub:"#6B7280",mt:"#9CA3AF",ln:"#E5E7EB"}};
const A={v:"#8B5CF6",pk:"#EC4899",or:"#F97316",cy:"#06B6D4",am:"#F59E0B",em:"#10B981",ro:"#F43F5E",sk:"#38BDF8"};
const GR={brand:`linear-gradient(135deg,${A.v},${A.pk})`,warm:`linear-gradient(135deg,${A.or},${A.ro})`,cool:`linear-gradient(135deg,#6366F1,${A.v})`,mint:`linear-gradient(135deg,${A.em},${A.cy})`,sun:`linear-gradient(135deg,${A.am},${A.or})`,trust:`linear-gradient(135deg,${A.ro},${A.or})`};
const GL=(c,r=16)=>`0 0 ${r}px ${c}30,0 4px 16px rgba(0,0,0,.3)`;
const AVATARS=["\uD83D\uDE0E","\uD83D\uDE00","\uD83E\uDD16","\uD83D\uDC2F","\uD83D\uDC38","\uD83D\uDD25","\uD83D\uDE80","\uD83D\uDC7B","\uD83E\uDDE0","\u26A1"];

/* ═══════ CONTEXT ═══════ */
const Ctx=createContext();
function useApp(){return useContext(Ctx);}

/* ═══════ AUDIO ═══════ */
let _a;const ac=()=>{if(!_a)_a=new(window.AudioContext||window.webkitAudioContext)();if(_a.state==="suspended")_a.resume();return _a;};
const bp=(f,d,w="sine",v=.18)=>{try{const c=ac(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.type=w;o.frequency.value=f;g.gain.setValueAtTime(v,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+d);o.start();o.stop(c.currentTime+d);}catch(_){}};
const sfx={tap:()=>bp(880,.06),tick:()=>bp(660,.1,"square",.12),go:()=>{bp(880,.12,"square",.2);setTimeout(()=>bp(1100,.16,"square",.16),70);},good:()=>{bp(523,.1);setTimeout(()=>bp(659,.1),80);setTimeout(()=>bp(784,.16),160);},great:()=>{[523,659,784,1047].forEach((f,i)=>setTimeout(()=>bp(f,.12),i*65));},bad:()=>{bp(380,.12,"sawtooth",.08);setTimeout(()=>bp(280,.2,"sawtooth",.06),100);},win:()=>{[523,659,784,1047,784,1047].forEach((f,i)=>setTimeout(()=>bp(f,.14),i*100));},elim:()=>{bp(200,.3,"sawtooth",.14);setTimeout(()=>bp(150,.4,"sawtooth",.09),160);},reveal:()=>{bp(330,.25,"triangle",.15);setTimeout(()=>bp(550,.3,"triangle",.12),250);},drama:()=>{[200,250,300,350,400,500,600,800].forEach((f,i)=>setTimeout(()=>bp(f,.1,"triangle",.08+i*.02),i*100));}};
const vb=p=>{try{navigator.vibrate?.(p);}catch(_){}};
const H={l:()=>vb(10),m:()=>vb(25),h:()=>vb([50,25,50]),ok:()=>vb([25,40,25,40,70])};

/* ═══════ CSS ═══════ */
const CSS=`*{box-sizing:border-box}
@keyframes pop{0%{transform:scale(.3);opacity:0}60%{transform:scale(1.06)}100%{transform:scale(1);opacity:1}}
@keyframes up{from{transform:translateY(20px);opacity:0}to{transform:translateY(0);opacity:1}}
@keyframes fadeIn{from{opacity:0}to{opacity:1}}
@keyframes cPop{0%{transform:scale(.5);opacity:0}50%{transform:scale(1.15)}100%{transform:scale(1);opacity:1}}
@keyframes float{0%,100%{transform:translateY(0)}50%{transform:translateY(-6px)}}
@keyframes breathe{0%,100%{transform:scale(1);opacity:.35}50%{transform:scale(1.12);opacity:.75}}
@keyframes ripple{0%{transform:scale(.8);opacity:.5}100%{transform:scale(2);opacity:0}}
@keyframes flash{0%{opacity:0;transform:scale(.5)}40%{opacity:1;transform:scale(1.1)}100%{transform:scale(1)}}
@keyframes conf{0%{transform:translateY(0) rotate(0);opacity:1}100%{transform:translateY(220px) rotate(720deg);opacity:0}}
@keyframes sL{from{transform:translateX(-14px);opacity:0}to{transform:translateX(0);opacity:1}}
@keyframes pulse{0%,100%{opacity:.5}50%{opacity:1}}
@keyframes dotP{0%,80%,100%{opacity:.3}40%{opacity:1}}
@keyframes shake{0%,100%{transform:translateX(0)}25%{transform:translateX(-6px)}75%{transform:translateX(6px)}}
@keyframes glow{0%,100%{filter:brightness(1)}50%{filter:brightness(1.3)}}`;

/* ═══════ HELPERS ═══════ */
function genTgt(r,d="medium",tm=false,iz=false){if(tm)return Math.round((15+Math.random()*10)*10)/10;if(iz){let lo,hi;if(r<=2){lo=3;hi=6;}else if(r<=5){lo=4;hi=8;}else{lo=5;hi=12;}return Math.round((lo+Math.random()*(hi-lo))*10)/10;}let lo,hi;if(r<=2){lo=1;hi=3;}else if(r<=5){lo=2;hi=6;}else{lo=3;hi=10;}let t=lo+Math.random()*(hi-lo);if(d==="easy")t=Math.round(t);else if(d==="medium")t=Math.round(t*10)/10;else t=Math.round(t*100)/100;return Math.max(lo,t);}
function fmt(t,d){return t.toFixed(d==="easy"?0:d==="medium"?1:2);}
function scoreMs(a,t){return Math.round(Math.abs(a-t)*1000);}
function grade(ms){if(ms<=30)return{k:"perf",c:A.am,i:"\u2B50"};if(ms<=100)return{k:"strong",c:A.em,i:"\uD83D\uDD25"};if(ms<=250)return{k:"good",c:A.v,i:"\uD83D\uDC4D"};if(ms<=500)return{k:"close",c:"#A5A3C8",i:"\uD83E\uDD14"};return{k:"miss",c:A.ro,i:"\uD83D\uDCA8"};}
function pts(ms,d){const tl=d==="easy"?500:d==="medium"?250:100;return Math.round(Math.max(0,1-ms/tl)*1000);}
const medal=r=>r===1?"\uD83E\uDD47":r===2?"\uD83E\uDD48":r===3?"\uD83E\uDD49":`#${r}`;

/* ═══════ ATOMS ═══════ */
function Btn({children,onClick,style,primary,small,disabled,gradient}){const{T}=useApp();const[p,sP]=useState(false);return <button onClick={()=>{if(disabled)return;sfx.tap();H.l();sP(true);setTimeout(()=>sP(false),150);onClick?.();}} style={{background:gradient||(primary?GR.brand:T.raised),border:primary||gradient?"none":`1px solid ${T.ln}`,borderRadius:small?10:14,padding:small?"10px 18px":"16px 36px",color:"#fff",fontSize:small?13:15,fontWeight:primary||gradient?800:600,letterSpacing:primary||gradient?1.5:0,cursor:disabled?"default":"pointer",textTransform:primary||gradient?"uppercase":"none",fontFamily:"inherit",transform:p?"scale(.94)":"scale(1)",transition:"transform .12s",opacity:disabled?.3:1,boxShadow:primary||gradient?GL(A.v,10):"none",...style}}>{children}</button>;}

function Buzzer({state,onTap,size=175,label}){const[p,sP]=useState(false);useEffect(()=>{if(state==="timing"){const i=setInterval(()=>sP(v=>!v),450);return()=>clearInterval(i);}sP(false);},[state]);const cfg={ready:{bg:GR.brand,lb:label||"START",sh:A.v},timing:{bg:GR.warm,lb:"STOP",sh:A.ro},done:{bg:`linear-gradient(135deg,#5D5B7A,#555)`,lb:"\u2713",sh:"#5D5B7A"}}[state]||{bg:GR.brand,lb:"",sh:A.v};const ok=state==="ready"||state==="timing";return <div style={{position:"relative",width:size,height:size,margin:"0 auto"}}><div style={{position:"absolute",inset:-10,borderRadius:"50%",background:cfg.sh,opacity:p?.2:.06,transition:"opacity .4s",filter:"blur(16px)"}}/><button onClick={ok?()=>{sfx.tap();H.m();onTap?.();}:undefined} style={{width:size,height:size,borderRadius:"50%",background:cfg.bg,border:"3px solid rgba(255,255,255,.2)",cursor:ok?"pointer":"default",display:"flex",alignItems:"center",justifyContent:"center",transform:p&&state==="timing"?"scale(1.03)":"scale(1)",transition:"transform .3s",boxShadow:GL(cfg.sh,24),position:"relative",zIndex:1,fontFamily:"inherit"}}><span style={{color:"#fff",fontSize:16,fontWeight:900,letterSpacing:4}}>{cfg.lb}</span></button></div>;}

function Confetti(){const cc=[A.v,A.pk,A.am,A.em,A.cy,A.or];return <div style={{position:"fixed",inset:0,pointerEvents:"none",overflow:"hidden",zIndex:999}}>{Array.from({length:30},(_,i)=><div key={i} style={{position:"absolute",top:-12,left:`${Math.random()*100}%`,width:5+Math.random()*8,height:5+Math.random()*8,borderRadius:i%3===0?"50%":2,background:cc[i%cc.length],animation:`conf ${1.2+Math.random()*1.3}s ease ${Math.random()*1.3}s forwards`}}/>)}</div>;}

function Countdown3({onDone}){const{t}=useApp();const[v,sV]=useState(3);useEffect(()=>{sfx.tick();H.l();const a=setTimeout(()=>{sV(2);sfx.tick();H.l();},1e3),b=setTimeout(()=>{sV(1);sfx.tick();H.m();},2e3),c=setTimeout(()=>{sV(0);sfx.go();H.h();},3e3),d=setTimeout(onDone,3500);return()=>{clearTimeout(a);clearTimeout(b);clearTimeout(c);clearTimeout(d);};},[]);return <div style={{textAlign:"center",padding:"50px 0"}}><div style={{fontSize:10,color:"#5D5B7A",letterSpacing:3,textTransform:"uppercase",marginBottom:8}}>{t("getReady")}</div><div key={v} style={{fontSize:96,fontWeight:900,background:v===0?GR.warm:GR.cool,WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent",animation:"cPop .3s ease"}}>{v===0?"GO!":v}</div></div>;}

/* ═══════ SETTINGS PICKER ═══════ */
function SPick({onDone,showDiff=true,title,sub2}){const{t,T}=useApp();const[d,sD]=useState(null);
  if(showDiff&&!d)return <div style={{animation:"up .4s ease",textAlign:"center"}}><div style={{fontSize:18,fontWeight:800,color:T.tx,marginBottom:4}}>{title||t("diff")}</div>{sub2&&<div style={{fontSize:12,color:T.sub,marginBottom:16}}>{sub2}</div>}<div style={{display:"flex",flexDirection:"column",gap:10,maxWidth:340,margin:"0 auto"}}>{[{id:"easy",k:"easy",dk:"easyD",gr:GR.mint,cl:A.em,ic:"\u2B50"},{id:"medium",k:"med",dk:"medD",gr:GR.sun,cl:A.am,ic:"\uD83D\uDD25"},{id:"hard",k:"hard",dk:"hardD",gr:GR.warm,cl:A.ro,ic:"\uD83D\uDCA5"}].map((x,i)=><button key={x.id} onClick={()=>{sfx.tap();sD(x.id);}} style={{background:T.card,borderRadius:16,border:`1px solid ${T.ln}`,padding:"16px 18px",display:"flex",alignItems:"center",gap:14,cursor:"pointer",fontFamily:"inherit",textAlign:"left",animation:`sL .3s ease ${i*.05}s both`}}><div style={{width:44,height:44,borderRadius:12,background:x.gr,display:"flex",alignItems:"center",justifyContent:"center",fontSize:18,flexShrink:0,boxShadow:GL(x.cl,8)}}>{x.ic}</div><div><div style={{fontSize:15,fontWeight:800,color:T.tx}}>{t(x.k)}</div><div style={{fontSize:11,color:T.sub}}>{t(x.dk)}</div></div></button>)}</div></div>;
  return <div style={{animation:"up .4s ease",textAlign:"center"}}><div style={{fontSize:18,fontWeight:800,color:T.tx,marginBottom:4}}>{t("rndCnt")}</div><div style={{fontSize:12,color:T.sub,marginBottom:20}}>{t("howMany")}</div><div style={{display:"flex",gap:12,justifyContent:"center"}}>{[1,3,5].map(r=><button key={r} onClick={()=>{sfx.tap();H.l();onDone(showDiff?d:"medium",r);}} style={{width:70,height:70,borderRadius:16,background:GR.brand,border:"none",color:"#fff",fontSize:28,fontWeight:900,cursor:"pointer",fontFamily:"inherit",boxShadow:GL(A.v,12),transition:"transform .15s"}} onMouseEnter={e=>e.currentTarget.style.transform="scale(1.08)"} onMouseLeave={e=>e.currentTarget.style.transform="scale(1)"}>{r}</button>)}</div></div>;
}

/* ═══════ CARD helper ═══════ */
function cd(T){return{background:T.card,borderRadius:16,border:`1px solid ${T.ln}`};}

/* ══════════════════════════════════════════
   SOLO MODE
   ══════════════════════════════════════════ */
function Solo({onBack}){const{t,T}=useApp();const[style,sS]=useState(null);const[cfg,sCfg]=useState(null);const[rnd,sRnd]=useState(1);const[tgt,sTgt]=useState(0);const[bs,sBs]=useState("ready");const[res,sRes]=useState(null);const[hist,sHist]=useState([]);const[phase,sPh]=useState("play");const tr=useRef(null);const tmr=useRef(null);const iRef=useRef(null);const[zR,sZR]=useState(null);const[zI,sZI]=useState("");const iz=style==="zeit";const C=cd(T);
  useEffect(()=>()=>{if(tmr.current)clearTimeout(tmr.current);},[]);
  if(!style)return <div><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:20}}><Btn onClick={onBack} small>{"\u2190"} {t("home")}</Btn></div><div style={{textAlign:"center",marginBottom:16}}><div style={{fontSize:18,fontWeight:800,color:T.tx}}>{t("soloT")}</div></div>{[{id:"normal",k:"normal",dk:"normalD",ic:"\uD83C\uDFAF",gr:GR.mint},{id:"zeit",k:"zeit",dk:"zeitD",ic:"\uD83E\uDDE0",gr:GR.brand}].map((m,i)=><button key={m.id} onClick={()=>{sfx.tap();sS(m.id);}} style={{...C,width:"100%",padding:"18px 20px",marginBottom:12,display:"flex",alignItems:"center",gap:14,cursor:"pointer",fontFamily:"inherit",textAlign:"left",animation:`sL .3s ease ${i*.05}s both`,background:m.gr,border:"none",borderRadius:18}}><div style={{fontSize:28}}>{m.ic}</div><div><div style={{fontSize:17,fontWeight:800,color:"#fff"}}>{t(m.k)}</div><div style={{fontSize:12,color:"rgba(255,255,255,.75)"}}>{t(m.dk)}</div></div><div style={{marginLeft:"auto",fontSize:20,color:"rgba(255,255,255,.5)"}}>{"\u203A"}</div></button>)}</div>;
  if(!cfg)return <div><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:20}}><Btn onClick={()=>sS(null)} small>{"\u2190"} {t("back")}</Btn></div><SPick onDone={(d,r)=>{sCfg({diff:d,rounds:r});sTgt(genTgt(1,d,false,iz));if(iz)sPh("countdown");else sPh("play");}} showDiff={!iz} title={iz?t("zeit"):t("normal")} sub2={t("soloMode")}/></div>;
  const tap=()=>{if(bs==="ready"){tr.current=Date.now();sBs("timing");}else if(bs==="timing"){const el=Math.max(.01,(Date.now()-tr.current)/1000);const ms=scoreMs(el,tgt);const p=pts(ms,cfg.diff);sBs("done");sRes({actual:el,tgt,ms,pts:p});sHist(h=>[...h,{r:rnd,actual:el,tgt,ms,pts:p}]);if(ms<=30){sfx.great();H.ok();}else if(ms<=250){sfx.good();H.m();}else{sfx.bad();H.l();}setTimeout(()=>sPh("result"),300);}};
  const zeitGo=()=>{const t0=Date.now();sZR(null);sZI("");sPh("zeitStart");setTimeout(()=>sPh("zeitRun"),1000);tmr.current=setTimeout(()=>{sZR(Math.round(((Date.now()-t0)/1000)*1e3)/1e3);sfx.good();H.h();sPh("zeitStop");setTimeout(()=>{sPh("zeitEst");setTimeout(()=>iRef.current?.focus(),120);},900);},tgt*1e3);};
  const zeitSubmit=()=>{const g=parseFloat(zI);if(isNaN(g)||g<=0)return;const ms=scoreMs(g,zR);const p=pts(ms,cfg.diff);sRes({actual:g,tgt:zR,ms,pts:p});sHist(h=>[...h,{r:rnd,actual:g,tgt:zR,ms,pts:p}]);if(ms<=30){sfx.great();H.ok();}else if(ms<=250){sfx.good();H.m();}else{sfx.bad();H.l();}sPh("result");};
  const next=()=>{if(rnd>=cfg.rounds){sPh("final");return;}const nr=rnd+1;sRnd(nr);sTgt(genTgt(nr,cfg.diff,false,iz));sBs("ready");sRes(null);sZR(null);sZI("");if(iz)sPh("countdown");else sPh("play");};
  const g=res?grade(res.ms):null;const tp=hist.reduce((a,h)=>a+h.pts,0);const ziOk=zI.trim()!==""&&!isNaN(parseFloat(zI))&&parseFloat(zI)>0;

  return <div><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:14}}><Btn onClick={onBack} small>{"\u2190"}</Btn><div style={{flex:1}}/><span style={{fontSize:11,color:T.sub}}>{iz?t("zeit"):t("normal")} · R{rnd}/{cfg.rounds}</span></div>
    {phase==="play"&&!iz&&<div style={{animation:"up .3s ease"}}><div style={{textAlign:"center",marginBottom:16}}><div style={{...C,display:"inline-block",padding:"12px 28px",borderLeft:`3px solid ${A.v}`}}><div style={{fontSize:9,color:T.mt,letterSpacing:2,textTransform:"uppercase"}}>{t("tgtTime")}</div><div style={{fontSize:44,fontWeight:900,color:T.tx,fontFamily:"monospace"}}>{fmt(tgt,cfg.diff)}<span style={{fontSize:16,color:T.mt}}>s</span></div></div></div><Buzzer state={bs} onTap={tap}/></div>}
    {phase==="countdown"&&iz&&<Countdown3 onDone={zeitGo}/>}
    {phase==="zeitStart"&&<div style={{textAlign:"center",padding:"50px 0",animation:"pop .3s ease"}}><div style={{fontSize:72,fontWeight:900,background:GR.mint,WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent",marginBottom:8}}>{t("now")}</div><div style={{fontSize:14,fontWeight:700,color:A.cy}}>{t("countNow")}</div></div>}
    {phase==="zeitRun"&&<div style={{textAlign:"center",padding:"40px 0",animation:"fadeIn .6s ease"}}><div style={{position:"relative",width:150,height:150,margin:"0 auto 18px"}}><div style={{position:"absolute",inset:0,borderRadius:"50%",border:`2px solid ${A.cy}22`,animation:"ripple 2s ease infinite"}}/><div style={{width:150,height:150,borderRadius:"50%",background:`radial-gradient(circle,${A.cy}10,transparent 70%)`,display:"flex",alignItems:"center",justifyContent:"center",animation:"breathe 3s ease infinite"}}><div style={{width:46,height:46,borderRadius:"50%",background:GR.cool,opacity:.5}}/></div></div><div style={{fontSize:16,fontWeight:700,color:A.cy}}>{t("countAlong")}</div><div style={{fontSize:12,color:T.mt,marginTop:4,fontStyle:"italic"}}>{t("timerSince")}</div></div>}
    {phase==="zeitStop"&&<div style={{textAlign:"center",padding:"50px 0",animation:"flash .35s ease"}}><div style={{fontSize:60,fontWeight:900,background:GR.warm,WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent"}}>{t("stop")}</div></div>}
    {phase==="zeitEst"&&<div style={{textAlign:"center",padding:"14px 0",animation:"up .4s ease"}}><div style={{fontSize:18,fontWeight:800,color:T.tx,marginBottom:16}}>{t("howLong")}</div><div style={{...C,display:"inline-block",padding:"18px 24px",borderTop:`3px solid ${A.cy}`,maxWidth:240}}><div style={{fontSize:9,color:T.mt,letterSpacing:2,textTransform:"uppercase",marginBottom:6}}>{t("yourEst")}</div><div style={{display:"flex",alignItems:"baseline",justifyContent:"center",gap:3}}><input ref={iRef} type="text" inputMode="decimal" placeholder="0.00" value={zI} onChange={e=>{const v=e.target.value.replace(/[^0-9.]/g,"");const p=v.split(".");sZI(p.length>2?p[0]+"."+p.slice(1).join(""):v);}} onKeyDown={e=>{if(e.key==="Enter"&&ziOk)zeitSubmit();}} style={{width:130,textAlign:"center",fontSize:42,fontWeight:900,color:zI?T.tx:T.mt,fontFamily:"monospace",border:"none",borderBottom:`3px solid ${zI?A.cy:T.ln}`,outline:"none",background:"transparent",padding:"3px 0"}}/><span style={{fontSize:18,color:T.mt}}>s</span></div></div><div style={{marginTop:16}}><Btn primary onClick={zeitSubmit} disabled={!ziOk}>{t("submit")}</Btn></div></div>}
    {phase==="result"&&res&&<div style={{animation:"pop .4s ease"}}><div style={{textAlign:"center",marginBottom:14}}><div style={{fontSize:44,animation:"float 2s ease infinite"}}>{g.i}</div><div style={{fontSize:26,fontWeight:900,color:g.c}}>{t(g.k)}</div></div><div style={{...C,padding:18,marginBottom:14}}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr 1fr",gap:8,textAlign:"center"}}>{[{l:iz?t("est"):t("yourTime"),v:`${res.actual.toFixed(3)}s`,c:A.cy},{l:iz?t("realT"):t("tgt"),v:`${res.tgt.toFixed(iz?3:(cfg.diff==="easy"?0:cfg.diff==="medium"?1:2))}s`,c:iz?A.v:T.sub},{l:t("dev"),v:`${res.ms}ms`,c:g.c},{l:t("pts"),v:res.pts,c:A.am}].map(s=><div key={s.l}><div style={{fontSize:8,color:T.mt,letterSpacing:1,textTransform:"uppercase"}}>{s.l}</div><div style={{fontSize:17,fontWeight:800,color:s.c,fontFamily:"monospace"}}>{s.v}</div></div>)}</div>{iz&&<div style={{marginTop:14}}>{[{l:t("realT"),v:res.tgt,c:A.cy},{l:t("est"),v:res.actual,c:A.am}].map((b,i)=>{const mx=Math.max(res.tgt,res.actual)*1.15;return <div key={i} style={{marginBottom:8}}><div style={{display:"flex",justifyContent:"space-between",fontSize:11,marginBottom:3}}><span style={{color:T.sub}}>{b.l}</span><span style={{color:b.c,fontWeight:800,fontFamily:"monospace"}}>{b.v.toFixed(3)}s</span></div><div style={{height:10,background:T.raised,borderRadius:5,overflow:"hidden"}}><div style={{height:"100%",borderRadius:5,background:b.c,width:`${(b.v/mx)*100}%`,transition:"width .6s ease"}}/></div></div>;})}<div style={{textAlign:"center",marginTop:8,fontSize:12,color:T.sub}}>{res.actual>res.tgt+.001?<span>{t("overEst")} <span style={{color:A.ro}}>+{(res.actual-res.tgt).toFixed(3)}s</span></span>:res.actual<res.tgt-.001?<span>{t("underEst")} <span style={{color:A.cy}}>{(res.actual-res.tgt).toFixed(3)}s</span></span>:<span style={{color:A.am,fontWeight:700}}>{t("perf")}</span>}</div></div>}</div><div style={{textAlign:"center"}}><Btn primary onClick={next}>{rnd>=cfg.rounds?t("result"):t("nextRnd")}</Btn></div></div>}
    {phase==="final"&&<div style={{animation:"pop .5s ease"}}><Confetti/><div style={{textAlign:"center",marginBottom:16}}><div style={{fontSize:56,animation:"float 2s ease infinite"}}>{"\uD83C\uDFC6"}</div><div style={{fontSize:24,fontWeight:900,background:`linear-gradient(135deg,${A.am},#FBBF24)`,WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent"}}>{tp} {t("pts")}</div></div><div style={{...C,padding:14,marginBottom:14}}><div style={{fontSize:9,color:T.mt,letterSpacing:2,textTransform:"uppercase",marginBottom:8}}>{t("allRnds")}</div>{hist.map((h,i)=><div key={i} style={{display:"flex",justifyContent:"space-between",padding:"6px 0",fontSize:12,borderBottom:i<hist.length-1?`1px solid ${T.ln}`:"none"}}><span style={{color:T.sub}}>R{h.r}</span><span style={{color:T.tx,fontFamily:"monospace"}}>{h.actual.toFixed(3)}s</span><span style={{color:grade(h.ms).c,fontWeight:700,fontFamily:"monospace"}}>{h.ms}ms</span><span style={{color:A.am,fontFamily:"monospace"}}>{h.pts}pt</span></div>)}</div><div style={{textAlign:"center"}}><Btn primary onClick={onBack}>{t("home")}</Btn></div></div>}
  </div>;
}

/* ══════════════════════════════════════════
   FFA ELIMINATION
   ══════════════════════════════════════════ */
function FFA({players,diff,rounds,isZeit,onBack}){const{t,T}=useApp();const C=cd(T);const[rnd,sRnd]=useState(1);const[tgt,sTgt]=useState(()=>genTgt(1,diff,false,isZeit));const[ci,sCi]=useState(0);const[bs,sBs]=useState("ready");const[rS,setRS]=useState({});const[sR,setSR]=useState(1);const[elim,sElim]=useState(new Set());const[phase,sPh]=useState("pre");const[results,setRes]=useState([]);const[winner,setWin]=useState(null);const[zR,setZR]=useState(null);const[zI,setZI]=useState("");const tr=useRef(null);const tmr=useRef(null);const iR=useRef(null);const[aS,setAS]=useState(()=>Object.fromEntries(players.map((_,i)=>[i,[]])));
  useEffect(()=>()=>{if(tmr.current)clearTimeout(tmr.current);},[]);
  const act=players.map((_,i)=>i).filter(i=>!elim.has(i));
  useEffect(()=>{if((phase==="pre")&&act.length)sCi(act[0]);},[phase]);
  const tap=()=>{if(bs==="ready"){tr.current=Date.now();sBs("timing");}else if(bs==="timing"){const el=Math.max(.01,(Date.now()-tr.current)/1000);sBs("done");fin(ci,el,scoreMs(el,tgt));}};
  const zGo=()=>{const t0=Date.now();setZR(null);setZI("");sPh("zeitStart");setTimeout(()=>sPh("zeitRun"),1000);tmr.current=setTimeout(()=>{setZR(Math.round(((Date.now()-t0)/1000)*1e3)/1e3);sfx.good();H.h();sPh("zeitStop");setTimeout(()=>{sPh("zeitEst");setTimeout(()=>iR.current?.focus(),120);},900);},tgt*1e3);};
  const zSub=()=>{const g=parseFloat(zI);if(isNaN(g)||g<=0)return;fin(ci,g,scoreMs(g,zR));};
  const fin=(idx,actual,ms)=>{const ns={...rS,[idx]:{actual,ms}};setRS(ns);const nas={...aS};if(!nas[idx])nas[idx]=[];nas[idx]=[...nas[idx],ms];setAS(nas);const rem=act.filter(i=>!(i in ns));
    if(rem.length){sCi(rem[0]);sBs("ready");setZR(null);setZI("");setTimeout(()=>sPh("pre"),400);}
    else{if(sR<rounds){setSR(sR+1);sTgt(genTgt(sR+1,diff,false,isZeit));setRS({});sBs("ready");setZR(null);setZI("");setTimeout(()=>sPh("pre"),400);}
    else{const ar=act.map(i=>{const sc=nas[i]||[];const avg=sc.length?Math.round(sc.reduce((a,b)=>a+b,0)/sc.length):99999;const sub=ns[i];return{idx:i,name:players[i].name,avg,actual:sub?.actual||0};}).sort((a,b)=>a.avg-b.avg);ar.forEach((r,i)=>{r.rank=i+1;r.out=false;});if(act.length>1)ar[ar.length-1].out=true;setRes(ar);sfx.good();H.m();if(ar.some(r=>r.out))setTimeout(()=>sfx.elim(),500);sPh("roundRes");}}};
  const nxt=()=>{const ne=new Set(elim);results.forEach(r=>{if(r.out)ne.add(r.idx);});sElim(ne);const na=players.map((_,i)=>i).filter(i=>!ne.has(i));if(na.length<=1){setWin(players[na[0]].name);sPh("final");return;}sRnd(r=>r+1);setSR(1);const nas2={};na.forEach(i=>{nas2[i]=[];});setAS(nas2);sTgt(genTgt(rnd+1,diff,false,isZeit));setRS({});sBs("ready");setZR(null);setZI("");sPh("pre");};

  return <div><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:12}}><Btn onClick={onBack} small>{"\u2190"}</Btn><div style={{flex:1}}/><span style={{fontSize:11,color:T.sub}}>{isZeit?t("zeit"):t("normal")} · FFA · {act.length} {t("remaining")}</span></div>
    {rounds>1&&<div style={{textAlign:"center",marginBottom:8}}><span style={{fontSize:10,color:T.mt,background:T.raised,padding:"3px 10px",borderRadius:20}}>{t("subRnd")} {sR}/{rounds}</span></div>}
    {phase==="pre"&&<div style={{textAlign:"center",padding:"32px 16px",animation:"up .4s ease"}}><div style={{fontSize:13,color:T.sub,marginBottom:12}}>{t("passPhone")}</div><div style={{fontSize:28,fontWeight:900,background:GR.brand,WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent",marginBottom:8}}>{players[ci]?.name}</div>{!isZeit&&<div style={{...C,display:"inline-block",padding:"10px 22px",borderLeft:`3px solid ${A.v}`,marginBottom:16}}><div style={{fontSize:9,color:T.mt,letterSpacing:2,textTransform:"uppercase"}}>{t("tgt")}</div><div style={{fontSize:34,fontWeight:900,color:T.tx,fontFamily:"monospace"}}>{fmt(tgt,diff)}s</div></div>}{isZeit&&<div style={{fontSize:12,color:A.cy,marginBottom:16}}>{t("tgtHidden")}</div>}<Btn primary onClick={()=>{if(isZeit)sPh("countdown");else{sBs("ready");sPh("play");}}}>{t("ready")}</Btn></div>}
    {phase==="countdown"&&<Countdown3 onDone={()=>{sBs("ready");if(isZeit)zGo();else sPh("play");}}/>}
    {phase==="zeitStart"&&<div style={{textAlign:"center",padding:"50px 0",animation:"pop .3s ease"}}><div style={{fontSize:72,fontWeight:900,background:GR.mint,WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent",marginBottom:8}}>{t("now")}</div><div style={{fontSize:14,fontWeight:700,color:A.cy}}>{players[ci]?.name} – {t("countNow")}</div></div>}
    {phase==="play"&&<div style={{animation:"up .3s ease"}}><div style={{textAlign:"center",marginBottom:10}}><span style={{fontSize:13,fontWeight:700,color:A.v}}>{players[ci]?.name}</span></div><div style={{textAlign:"center",marginBottom:14}}><div style={{...C,display:"inline-block",padding:"10px 20px",borderLeft:`3px solid ${A.v}`}}><div style={{fontSize:9,color:T.mt,letterSpacing:2,textTransform:"uppercase"}}>{t("tgt")}</div><div style={{fontSize:32,fontWeight:900,color:T.tx,fontFamily:"monospace"}}>{fmt(tgt,diff)}s</div></div></div><Buzzer state={bs} onTap={tap}/></div>}
    {phase==="zeitRun"&&<div style={{textAlign:"center",padding:"36px 0",animation:"fadeIn .5s ease"}}><div style={{position:"relative",width:130,height:130,margin:"0 auto 16px"}}><div style={{position:"absolute",inset:0,borderRadius:"50%",border:`2px solid ${A.cy}22`,animation:"ripple 2s ease infinite"}}/><div style={{width:130,height:130,borderRadius:"50%",background:`radial-gradient(circle,${A.cy}10,transparent 70%)`,display:"flex",alignItems:"center",justifyContent:"center",animation:"breathe 3s ease infinite"}}><div style={{width:40,height:40,borderRadius:"50%",background:GR.cool,opacity:.5}}/></div></div><div style={{fontSize:14,fontWeight:700,color:A.cy}}>{players[ci]?.name} – {t("countAlong")}</div><div style={{fontSize:11,color:T.mt,marginTop:4,fontStyle:"italic"}}>{t("timerSince")}</div></div>}
    {phase==="zeitStop"&&<div style={{textAlign:"center",padding:"46px 0",animation:"flash .35s ease"}}><div style={{fontSize:54,fontWeight:900,background:GR.warm,WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent"}}>{t("stop")}</div></div>}
    {phase==="zeitEst"&&<div style={{textAlign:"center",padding:"12px 0",animation:"up .4s ease"}}><div style={{fontSize:14,fontWeight:800,color:T.tx,marginBottom:6}}>{players[ci]?.name}: {t("yourEst")}</div><div style={{...C,display:"inline-block",padding:"14px 20px",borderTop:`3px solid ${A.cy}`,maxWidth:220,marginBottom:12}}><div style={{display:"flex",alignItems:"baseline",justifyContent:"center",gap:3}}><input ref={iR} type="text" inputMode="decimal" placeholder="0.00" value={zI} onChange={e=>setZI(e.target.value.replace(/[^0-9.]/g,""))} onKeyDown={e=>{if(e.key==="Enter")zSub();}} style={{width:110,textAlign:"center",fontSize:36,fontWeight:900,color:zI?T.tx:T.mt,fontFamily:"monospace",border:"none",borderBottom:`3px solid ${zI?A.cy:T.ln}`,outline:"none",background:"transparent"}}/><span style={{fontSize:16,color:T.mt}}>s</span></div></div><Btn primary onClick={zSub} disabled={!zI||isNaN(parseFloat(zI))}>{t("submit")}</Btn></div>}
    {phase==="roundRes"&&<div style={{maxWidth:380,margin:"0 auto",animation:"up .3s ease"}}><div style={{textAlign:"center",marginBottom:14}}><div style={{fontSize:11,color:T.mt,letterSpacing:3,textTransform:"uppercase"}}>{t("elimRnd")} {rnd}</div>{rounds>1&&<div style={{fontSize:10,color:T.sub,marginTop:2}}>{t("avgOver")} {rounds} {t("rnds")}</div>}</div>{results.map((r,i)=><div key={r.idx} style={{display:"flex",alignItems:"center",gap:10,...C,padding:"11px 14px",marginBottom:7,background:r.out?`${A.ro}15`:T.card,borderLeft:`3px solid ${r.out?A.ro:grade(r.avg).c}`,animation:`sL .4s ease ${i*.08}s both`}}><div style={{fontSize:20,width:30,textAlign:"center"}}>{r.out?"\uD83D\uDC80":medal(r.rank)}</div><div style={{flex:1}}><div style={{fontWeight:700,fontSize:13,color:r.out?A.ro:T.tx,textDecoration:r.out?"line-through":"none"}}>{r.name}</div></div><div style={{fontFamily:"monospace",fontWeight:800,fontSize:14,color:grade(r.avg).c}}>{"\u00D8"} {r.avg}ms</div></div>)}{results.some(r=>r.out)&&<div style={{textAlign:"center",color:A.ro,fontSize:13,fontWeight:700,margin:"8px 0",animation:"shake .5s ease"}}>{"\uD83D\uDC80"} {results.find(r=>r.out)?.name} {t("isOut")}</div>}<div style={{textAlign:"center",marginTop:14}}><Btn primary onClick={nxt}>{t("next")}</Btn></div></div>}
    {phase==="final"&&<div style={{animation:"pop .5s ease"}}><Confetti/><div style={{textAlign:"center",marginBottom:16}}><div style={{fontSize:60,animation:"float 2s ease infinite"}}>{"\uD83C\uDFC6"}</div><div style={{fontSize:28,fontWeight:900,background:`linear-gradient(135deg,${A.am},#FBBF24)`,WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent"}}>{winner}</div><div style={{fontSize:12,color:T.sub,marginTop:4}}>{t("winsTrn")}</div></div><div style={{textAlign:"center"}}><Btn primary onClick={onBack}>{t("home")}</Btn></div></div>}
  </div>;
}

/* ══════════════════════════════════════════
   TEAM VS TEAM
   ══════════════════════════════════════════ */
function TeamGame({players,diff,rounds,onBack}){const{t,T}=useApp();const C=cd(T);const t1=players.filter(p=>p.team===1);const t2=players.filter(p=>p.team===2);const[rnd,sRnd]=useState(1);const[tgt,sTgt]=useState(()=>genTgt(1,diff,true));const[phase,sPh]=useState("info");const[t1C,sT1C]=useState(0);const[t2C,sT2C]=useState(0);const[t1I,sT1I]=useState(0);const[t2I,sT2I]=useState(0);const[bs,sBs]=useState("ready");const[rH,sRH]=useState([]);const[cR,sCR]=useState(null);const[win,sWin]=useState(null);const tr=useRef(null);
  const cT=phase==="t1play"?1:2;const cP=cT===1?t1:t2;const cI=cT===1?t1I:t2I;const cCh=cT===1?t1C:t2C;
  const tap=()=>{if(bs==="ready"){tr.current=Date.now();sBs("timing");}else if(bs==="timing"){const el=Math.max(.01,(Date.now()-tr.current)/1000);const nc=cCh+el;sBs("done");if(cT===1){sT1C(nc);if(t1I<t1.length-1){sT1I(t1I+1);sBs("ready");setTimeout(()=>sPh("t1play"),400);}else{sT2I(0);sT2C(0);sBs("ready");sPh("t2play");}}else{sT2C(nc);if(t2I<t2.length-1){sT2I(t2I+1);sBs("ready");setTimeout(()=>sPh("t2play"),400);}else{const f1=t1C,f2=nc,m1=scoreMs(f1,tgt),m2=scoreMs(f2,tgt);const r={rnd,tgt,t1:f1,t2:f2,t1ms:m1,t2ms:m2,w:m1<m2?1:m2<m1?2:0};sCR(r);sRH(h=>[...h,r]);sfx.good();H.m();sPh("result");}}}};
  const lr=cR;
  const nR=()=>{if(rnd>=rounds){const w1=rH.filter(r=>r.w===1).length,w2=rH.filter(r=>r.w===2).length;sWin(w1>w2?"Team 1":w2>w1?"Team 2":"Unentschieden");sPh("final");return;}sRnd(r=>r+1);sTgt(genTgt(rnd+1,diff,true));sT1C(0);sT2C(0);sT1I(0);sT2I(0);sBs("ready");sCR(null);sPh("info");};

  return <div><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:12}}><Btn onClick={onBack} small>{"\u2190"}</Btn><div style={{flex:1}}/><span style={{fontSize:11,color:T.sub}}>Team · R{rnd}/{rounds}</span></div>
    {phase==="info"&&<div style={{textAlign:"center",padding:"24px 16px",animation:"up .4s ease"}}><div style={{fontSize:18,fontWeight:800,color:T.tx,marginBottom:8}}>{t("rnd")} {rnd}</div><div style={{...C,padding:16,marginBottom:16,borderLeft:`3px solid ${A.am}`}}><div style={{fontSize:9,color:T.mt,letterSpacing:2,textTransform:"uppercase"}}>{t("teamTgt")}</div><div style={{fontSize:40,fontWeight:900,color:A.am,fontFamily:"monospace"}}>{tgt.toFixed(1)}s</div><div style={{fontSize:11,color:T.sub,marginTop:6,lineHeight:1.6}}>{t("teamInfo")}</div></div><Btn primary onClick={()=>{sT1I(0);sT1C(0);sBs("ready");sPh("t1play");}}>{t("t1Start")}</Btn></div>}
    {(phase==="t1play"||phase==="t2play")&&<div style={{animation:"up .3s ease"}}><div style={{textAlign:"center",marginBottom:6}}><span style={{fontSize:10,color:T.mt,letterSpacing:2,textTransform:"uppercase"}}>Team {cT}</span></div><div style={{textAlign:"center",marginBottom:8}}><span style={{fontSize:20,fontWeight:800,color:cT===1?A.v:A.pk}}>{cP[cI]?.name}</span></div><div style={{textAlign:"center",marginBottom:6,fontSize:11,color:T.sub}}>{t("player")} {cI+1}/{cP.length}</div><Buzzer state={bs} onTap={tap} label={bs==="ready"?"+ZEIT":"STOP"}/><div style={{textAlign:"center",marginTop:10}}><div style={{...C,display:"inline-block",padding:"6px 16px"}}><span style={{fontSize:10,color:T.mt}}>{t("tgt")}: </span><span style={{fontSize:14,fontWeight:800,color:A.am,fontFamily:"monospace"}}>{tgt.toFixed(1)}s</span></div></div></div>}
    {phase==="result"&&lr&&<div style={{animation:"pop .4s ease",textAlign:"center"}}><div style={{fontSize:14,fontWeight:800,color:T.tx,marginBottom:12}}>{t("rnd")} {lr.rnd}</div><div style={{display:"flex",gap:10,justifyContent:"center",marginBottom:14}}>{[{tm:1,time:lr.t1,ms:lr.t1ms,c:A.v},{tm:2,time:lr.t2,ms:lr.t2ms,c:A.pk}].map(x=><div key={x.tm} style={{...C,flex:1,padding:14,textAlign:"center",borderTop:`3px solid ${x.c}`,background:lr.w===x.tm?`${x.c}15`:T.card}}><div style={{fontSize:10,color:T.mt}}>Team {x.tm}</div><div style={{fontSize:22,fontWeight:900,color:x.c,fontFamily:"monospace"}}>{x.time.toFixed(2)}s</div><div style={{fontSize:12,color:grade(x.ms).c,fontWeight:700,marginTop:4}}>{x.ms}ms {t("devMs")}</div>{lr.w===x.tm&&<div style={{fontSize:11,color:A.am,fontWeight:800,marginTop:4}}>{"\uD83C\uDFC6"} {t("won")}</div>}</div>)}</div><div style={{...C,padding:10,marginBottom:14}}><span style={{fontSize:11,color:T.mt}}>{t("tgtWas")}: </span><span style={{fontSize:14,fontWeight:800,color:A.am,fontFamily:"monospace"}}>{lr.tgt.toFixed(1)}s</span></div><Btn primary onClick={nR}>{rnd>=rounds?t("result"):t("nextRnd")}</Btn></div>}
    {phase==="final"&&<div style={{animation:"pop .5s ease"}}><Confetti/><div style={{textAlign:"center",marginBottom:16}}><div style={{fontSize:56,animation:"float 2s ease infinite"}}>{"\uD83C\uDFC6"}</div><div style={{fontSize:28,fontWeight:900,background:`linear-gradient(135deg,${A.am},#FBBF24)`,WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent"}}>{win}</div></div><div style={{display:"flex",gap:10,justifyContent:"center",marginBottom:14}}>{[1,2].map(tm=><div key={tm} style={{...C,flex:1,padding:14,textAlign:"center",borderTop:`3px solid ${tm===1?A.v:A.pk}`}}><div style={{fontSize:10,color:T.mt}}>Team {tm}</div><div style={{fontSize:22,fontWeight:900,color:tm===1?A.v:A.pk}}>{rH.filter(r=>r.w===tm).length}</div><div style={{fontSize:11,color:T.sub}}>{t("wins")}</div></div>)}</div><div style={{textAlign:"center"}}><Btn primary onClick={onBack}>{t("home")}</Btn></div></div>}
  </div>;
}

/* ══════════════════════════════════════════
   MULTIHUB
   ══════════════════════════════════════════ */
function MultiHub({onBack}){const{t,T}=useApp();const C=cd(T);const[step,sStep]=useState("style");const[style,sStyle]=useState(null);const[type,sType]=useState(null);const[myName,sMyN]=useState("");const[myAv,sMyA]=useState(AVATARS[0]);const[code,sCode]=useState("");const[players,sPl]=useState([]);const[rnds,sRnds]=useState(3);const[addName,sAN]=useState("");const[addAv,sAA]=useState(AVATARS[1]);
  const genCode=()=>Array.from({length:6},()=>"ABCDEFGHJKLMNPQRSTUVWXYZ23456789"[Math.floor(Math.random()*31)]).join("");
  const back=()=>{if(step==="style")onBack();else if(step==="type")sStep("style");else if(step==="setup")sStep("type");else if(step==="joinCode")sStep("setup");else if(step==="lobby")sStep("setup");else onBack();};
  if(step==="game"){const pl=players.map((p,i)=>({name:p.name,team:type==="team"?(p.team||((i<Math.ceil(players.length/2))?1:2)):0}));if(type==="team")return <TeamGame players={pl} diff="medium" rounds={rnds} onBack={onBack}/>;return <FFA players={pl} diff="medium" rounds={rnds} isZeit={style==="zeit"} onBack={onBack}/>;}
  const minPl=type==="team"?4:2;
  const copyCode=()=>{try{navigator.clipboard?.writeText(code);}catch(_){}sfx.tap();};
  const addP=()=>{if(!addName.trim()||players.length>=10)return;sfx.tap();H.l();sPl(p=>[...p,{name:addName.trim(),avatar:addAv,team:players.length%2===0?1:2}]);sAN("");sAA(AVATARS[(players.length+2)%AVATARS.length]);};

  return <div style={{maxWidth:400,margin:"0 auto"}}><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:16}}><Btn onClick={back} small>{"\u2190"}</Btn><div style={{flex:1}}/><span style={{fontSize:11,color:T.mt}}>{t("multi")}</span></div>

    {step==="style"&&<div style={{animation:"up .4s ease"}}><div style={{textAlign:"center",marginBottom:16}}><div style={{fontSize:18,fontWeight:800,color:T.tx}}>{t("howPlay")}</div></div>{[{id:"normal",k:"normal",dk:"normalD",ic:"\uD83C\uDFAF",gr:GR.mint},{id:"zeit",k:"zeit",dk:"zeitD",ic:"\uD83E\uDDE0",gr:GR.brand}].map((m,i)=><button key={m.id} onClick={()=>{sfx.tap();sStyle(m.id);sStep("type");}} style={{...C,width:"100%",padding:"18px 20px",marginBottom:12,display:"flex",alignItems:"center",gap:14,cursor:"pointer",fontFamily:"inherit",textAlign:"left",animation:`sL .3s ease ${i*.05}s both`,background:m.gr,border:"none",borderRadius:18}}><div style={{fontSize:28}}>{m.ic}</div><div><div style={{fontSize:17,fontWeight:800,color:"#fff"}}>{t(m.k)}</div><div style={{fontSize:12,color:"rgba(255,255,255,.75)"}}>{t(m.dk)}</div></div><div style={{marginLeft:"auto",fontSize:20,color:"rgba(255,255,255,.5)"}}>{"\u203A"}</div></button>)}</div>}

    {step==="type"&&<div style={{animation:"up .4s ease"}}><div style={{textAlign:"center",marginBottom:16}}><div style={{fontSize:18,fontWeight:800,color:T.tx}}>{t("withWhom")}</div></div>{[{id:"ffa",k:"ffa",dk:"ffaD",ic:"\u2694\uFE0F",gr:`linear-gradient(135deg,${A.sk},${A.cy})`},{id:"team",k:"team",dk:"teamD",ic:"\uD83E\uDD1D",gr:`linear-gradient(135deg,${A.pk},${A.ro})`}].map((m,i)=><button key={m.id} onClick={()=>{sfx.tap();sType(m.id);sStep("setup");}} style={{...C,width:"100%",padding:"18px 20px",marginBottom:12,display:"flex",alignItems:"center",gap:14,cursor:"pointer",fontFamily:"inherit",textAlign:"left",animation:`sL .3s ease ${i*.05}s both`,background:m.gr,border:"none",borderRadius:18}}><div style={{fontSize:28}}>{m.ic}</div><div><div style={{fontSize:17,fontWeight:800,color:"#fff"}}>{t(m.k)}</div><div style={{fontSize:12,color:"rgba(255,255,255,.75)"}}>{t(m.dk)}</div></div><div style={{marginLeft:"auto",fontSize:20,color:"rgba(255,255,255,.5)"}}>{"\u203A"}</div></button>)}</div>}

    {step==="setup"&&<div style={{animation:"up .4s ease"}}>
      <div style={{...C,padding:"18px 20px",marginBottom:16,textAlign:"center",background:T.raised}}><div style={{fontSize:36,marginBottom:6}}>{type==="ffa"?"\uD83C\uDFC6":"\uD83E\uDD1D"}</div><div style={{fontSize:18,fontWeight:800,color:T.tx}}>{type==="ffa"?t("tourn"):t("team")}</div><div style={{fontSize:12,color:T.sub,marginTop:2}}>{type==="ffa"?t("tournD"):t("teamD")}</div></div>
      <div style={{...C,padding:"18px 20px",marginBottom:16}}>
        <input value={myName} onChange={e=>sMyN(e.target.value)} placeholder={t("name")} maxLength={12} style={{width:"100%",background:"transparent",border:"none",borderBottom:`2px solid ${myName?A.v:T.ln}`,padding:"10px 0",color:T.tx,fontSize:18,fontWeight:800,outline:"none",fontFamily:"inherit",textAlign:"center"}}/>
        <div style={{fontSize:10,color:T.mt,letterSpacing:2,textTransform:"uppercase",textAlign:"center",marginTop:16,marginBottom:10}}>{t("avatar")}</div>
        <div style={{display:"grid",gridTemplateColumns:"repeat(5,1fr)",gap:8}}>{AVATARS.map(a=><button key={a} onClick={()=>{sfx.tap();sMyA(a);}} style={{width:"100%",aspectRatio:"1",borderRadius:12,background:myAv===a?`${A.v}30`:T.raised,border:myAv===a?`2px solid ${A.v}`:`1px solid ${T.ln}`,fontSize:24,cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center"}}>{a}</button>)}</div>
      </div>
      <div style={{display:"flex",gap:14,justifyContent:"center"}}>
        <div style={{textAlign:"center"}}><button onClick={()=>{if(!myName.trim())return;sfx.tap();H.l();sCode(genCode());sPl([{name:myName.trim(),avatar:myAv,host:true,team:1}]);sStep("lobby");}} disabled={!myName.trim()} style={{width:80,height:80,borderRadius:"50%",border:"none",cursor:myName.trim()?"pointer":"default",background:myName.trim()?GR.mint:T.raised,fontSize:28,color:"#fff",display:"flex",alignItems:"center",justifyContent:"center",boxShadow:myName.trim()?GL(A.em,14):"none",opacity:myName.trim()?1:.3}}>+</button><div style={{fontSize:12,color:T.sub,marginTop:6,fontWeight:600}}>{t("create")}</div></div>
        <div style={{textAlign:"center"}}><button onClick={()=>{if(!myName.trim())return;sfx.tap();H.l();sStep("joinCode");}} disabled={!myName.trim()} style={{width:80,height:80,borderRadius:"50%",border:"none",cursor:myName.trim()?"pointer":"default",background:myName.trim()?`linear-gradient(135deg,${A.sk},${A.cy})`:T.raised,fontSize:28,color:"#fff",display:"flex",alignItems:"center",justifyContent:"center",boxShadow:myName.trim()?GL(A.sk,14):"none",opacity:myName.trim()?1:.3}}>{"\u2192"}</button><div style={{fontSize:12,color:T.sub,marginTop:6,fontWeight:600}}>{t("join")}</div></div>
      </div>
    </div>}

    {step==="joinCode"&&<div style={{animation:"up .4s ease",textAlign:"center"}}>
      <div style={{fontSize:36,marginBottom:8}}>{"\uD83D\uDD11"}</div>
      <div style={{fontSize:18,fontWeight:800,color:T.tx,marginBottom:14}}>{t("joinRoom")}</div>
      <input value={code} onChange={e=>sCode(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,6))} placeholder="CODE" maxLength={6} style={{width:"100%",maxWidth:260,background:T.raised,border:`2px solid ${code.length===6?A.v:T.ln}`,borderRadius:14,padding:"16px",color:T.tx,fontSize:26,fontWeight:900,fontFamily:"monospace",outline:"none",textAlign:"center",letterSpacing:8}}/>
      <div style={{marginTop:16}}><Btn primary onClick={()=>{if(code.length<6)return;sfx.tap();sPl([{name:"Host",avatar:"\uD83D\uDE0E",host:true,team:1},{name:myName.trim(),avatar:myAv,host:false,team:2}]);sStep("lobby");}} disabled={code.length<6}>{t("join")}</Btn></div>
    </div>}

    {step==="lobby"&&<div style={{animation:"up .4s ease",textAlign:"center"}}>
      <button onClick={copyCode} style={{...C,display:"inline-block",padding:"12px 28px",marginBottom:16,background:T.raised,cursor:"pointer",fontFamily:"inherit"}}><div style={{fontSize:9,color:T.mt,letterSpacing:2,textTransform:"uppercase"}}>{t("roomCode")}</div><div style={{fontSize:34,fontWeight:900,color:A.am,fontFamily:"monospace",letterSpacing:8}}>{code}</div><div style={{fontSize:10,color:A.v,marginTop:2}}>{"\uD83D\uDCCB"} {t("shareCode")}</div></button>
      <div style={{fontSize:12,color:T.sub,marginBottom:12}}>{style==="zeit"?"\uD83E\uDDE0 "+t("zeit"):"\uD83C\uDFAF "+t("normal")} · {type==="ffa"?t("ffa"):t("team")}</div>
      <div style={{...C,padding:14,marginBottom:14,textAlign:"left"}}>
        <div style={{fontSize:10,color:T.mt,letterSpacing:2,textTransform:"uppercase",marginBottom:10}}>{t("players")} ({players.length})</div>
        {players.map((p,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:10,padding:"10px 0",borderBottom:i<players.length-1?`1px solid ${T.ln}`:"none"}}><div style={{fontSize:24}}>{p.avatar}</div><div style={{flex:1}}><span style={{fontWeight:700,fontSize:14,color:T.tx}}>{p.name}</span>{p.host&&<span style={{fontSize:9,color:A.am,marginLeft:6,fontWeight:700,background:`${A.am}20`,padding:"2px 6px",borderRadius:4}}>HOST</span>}</div>{type==="team"&&<button onClick={()=>{const a=[...players];a[i]={...a[i],team:a[i].team===1?2:1};sPl(a);}} style={{fontSize:10,color:p.team===1?A.v:A.pk,fontWeight:700,background:`${p.team===1?A.v:A.pk}20`,padding:"3px 8px",borderRadius:6,border:"none",cursor:"pointer",fontFamily:"inherit"}}>T{p.team}</button>}{!p.host&&<button onClick={()=>sPl(pl=>pl.filter((_,j)=>j!==i))} style={{background:"none",border:"none",color:A.ro,cursor:"pointer",fontSize:14}}>{"\u2715"}</button>}</div>)}
      </div>
      {players.length<10&&<div style={{...C,padding:"12px 16px",marginBottom:14}}><div style={{display:"flex",gap:8,alignItems:"center"}}><input value={addName} onChange={e=>sAN(e.target.value)} placeholder={`${t("player")}...`} maxLength={12} onKeyDown={e=>{if(e.key==="Enter")addP();}} style={{flex:1,background:"transparent",border:"none",borderBottom:`2px solid ${addName?A.v:T.ln}`,padding:"6px 0",color:T.tx,fontSize:14,fontWeight:700,outline:"none",fontFamily:"inherit",textAlign:"center"}}/><select value={addAv} onChange={e=>{sAA(e.target.value);}} style={{fontSize:22,background:"transparent",border:"none",cursor:"pointer"}}>{AVATARS.map(a=><option key={a} value={a}>{a}</option>)}</select><button onClick={addP} disabled={!addName.trim()} style={{width:36,height:36,borderRadius:10,background:addName.trim()?GR.mint:T.raised,border:"none",color:"#fff",fontSize:18,cursor:addName.trim()?"pointer":"default",opacity:addName.trim()?1:.3}}>+</button></div></div>}
      <div style={{display:"flex",alignItems:"center",justifyContent:"center",gap:10,marginBottom:14}}><span style={{fontSize:12,color:T.sub}}>{t("rnds")}:</span>{[1,3,5].map(r=><button key={r} onClick={()=>{sfx.tap();sRnds(r);}} style={{width:38,height:38,borderRadius:10,border:"none",background:rnds===r?GR.brand:T.raised,color:"#fff",fontWeight:800,fontSize:15,cursor:"pointer"}}>{r}</button>)}</div>
      <Btn primary onClick={()=>sStep("game")} disabled={players.length<minPl} style={{width:"100%",maxWidth:300}}>{t("startGame")}</Btn>
    </div>}
  </div>;
}

/* ══════════════════════════════════════════
   TRUST BREAKER
   ══════════════════════════════════════════ */
function TrustBreaker({onBack}){const{t,T}=useApp();const C=cd(T);const[step,sStep]=useState("setup");const[myName,sMyN]=useState("");const[myAv,sMyA]=useState(AVATARS[0]);const[code,sCode]=useState("");const[lobby,sLobby]=useState([]);const[addName,sAN]=useState("");const[addAv,sAA]=useState(AVATARS[1]);const[pl,sPl]=useState([]);const[tRnd,sTR]=useState(3);const[roles,sRoles]=useState({});const[rrI,sRRI]=useState(0);const[rrS,sRRS]=useState(false);const[rnd,sRnd]=useState(1);const[tgt,sTgt]=useState(3);const[ci,sCi]=useState(0);const[bs,sBs]=useState("ready");const[raw,sRaw]=useState({});const[fin,sFin]=useState({});const[fU,sFU]=useState(false);const[sU,sSU]=useState(false);const[hP,sHP]=useState(null);const[votes,sVotes]=useState({});const[vI,sVI]=useState(0);const[vF,sVF]=useState(null);const[vS,sVS]=useState(null);const[ard,sARD]=useState([]);const tr=useRef(null);
  const n=pl.length;const fI=Object.entries(roles).find(([,r])=>r==="fake")?.[0];const sI=Object.entries(roles).find(([,r])=>r==="saboteur")?.[0];const fIdx=fI!==undefined?parseInt(fI):-1;const sIdx=sI!==undefined?parseInt(sI):-1;
  const genCode=()=>Array.from({length:6},()=>"ABCDEFGHJKLMNPQRSTUVWXYZ23456789"[Math.floor(Math.random()*31)]).join("");
  const copyCode=()=>{try{navigator.clipboard?.writeText(code);}catch(_){}sfx.tap();};
  const addP=()=>{if(!addName.trim()||lobby.length>=6)return;sfx.tap();H.l();sLobby(l=>[...l,{name:addName.trim(),avatar:addAv}]);sAN("");sAA(AVATARS[(lobby.length+2)%AVATARS.length]);};
  const startG=()=>{const p=lobby.map(x=>({n:x.name,avatar:x.avatar}));sPl(p);sStep("assigning");setTimeout(()=>{const r={};p.forEach((_,i)=>{r[i]="normal";});const idx=[...Array(p.length).keys()].sort(()=>Math.random()-.5);r[idx[0]]="fake";r[idx[1]]="saboteur";sRoles(r);sRRI(0);sRRS(false);sfx.drama();setTimeout(()=>sStep("roleReveal"),600);},2200);};
  const back2=()=>{if(step==="setup")onBack();else if(step==="joinCode")sStep("setup");else if(step==="lobby")sStep("setup");else onBack();};
  const nextRR=()=>{if(rrI<n-1){sRRI(rrI+1);sRRS(false);}else{sTgt(genTgt(1,"medium"));sRnd(1);sCi(0);sRaw({});sFin({});sFU(false);sARD([]);sStep("roundPre");}};
  const tap=()=>{if(bs==="ready"){tr.current=Date.now();sBs("timing");}else if(bs==="timing"){const e=Math.max(.01,(Date.now()-tr.current)/1000);sBs("done");const nr={...raw,[ci]:e};sRaw(nr);if(ci<n-1){sCi(ci+1);sBs("ready");setTimeout(()=>sStep("roundPre"),400);}else{sFin({...nr});sHP("loading");sStep("hidden");setTimeout(()=>{if(!fU)sHP("fake");else if(!sU)sHP("sab");else sHP("done");},2000);}}};
  const fakeAct=(dir)=>{const ft={...fin};ft[fIdx]=raw[fIdx]+(dir==="plus"?.4:-.4);sFin(ft);sFU(true);sHP("loading");setTimeout(()=>{if(!sU)sHP("sab");else sHP("done");},1500);};
  const fakeSkip=()=>{sFU(true);sHP("loading");setTimeout(()=>{if(!sU)sHP("sab");else sHP("done");},1500);};
  const sabAct=(tI)=>{const ft={...fin};const ac=ft[tI]||raw[tI];const dv=ac-tgt;ft[tI]=ac+(dv>=0?.3:-.3);sFin(ft);sSU(true);sHP("loading");setTimeout(()=>sHP("done"),1200);};
  const sabSkip=()=>{sSU(true);sHP("loading");setTimeout(()=>sHP("done"),1200);};
  useEffect(()=>{if(hP==="done")setTimeout(()=>{const rd=pl.map((p,i)=>{const tm=fin[i]||raw[i]||0;const ms=Math.round(Math.abs(tm-tgt)*1e3);const st=ms<=80?"sehr nah":ms<=250?"nah":"auffällig";return{idx:i,name:p.n,time:tm,ms,status:st};}).sort((a,b)=>a.ms-b.ms).map((r,i)=>({...r,rank:i+1}));sARD(prev=>[...prev,{rnd,tgt,results:rd}]);sfx.reveal();sStep("roundResult");},800);},[hP]);
  const curRes=()=>ard[ard.length-1]?.results||[];
  const nextRound=()=>{if(rnd>=tRnd){sVI(0);sVotes({});sVF(null);sVS(null);sfx.drama();sStep("vote");return;}sRnd(rnd+1);sTgt(genTgt(rnd+1,"medium"));sCi(0);sBs("ready");sRaw({});sFin({});sFU(false);sHP(null);sStep("roundPre");};
  const subVote=()=>{if(vF===null||vS===null)return;const nv={...votes,[vI]:{fake:vF,sab:vS}};sVotes(nv);sVF(null);sVS(null);if(vI<n-1)sVI(vI+1);else{sfx.drama();setTimeout(()=>sStep("reveal"),800);}};
  const stL=ms=>ms<=80?{c:A.em}:ms<=250?{c:A.am}:{c:A.ro};

  return <div style={{maxWidth:400,margin:"0 auto"}}><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:14}}><Btn onClick={back2} small>{"\u2190"}</Btn><div style={{flex:1}}/><span style={{fontSize:11,color:T.sub}}>{t("tbTitle")}</span></div>

    {step==="setup"&&<div style={{animation:"up .4s ease"}}>
      <div style={{...C,padding:"18px 20px",marginBottom:16,textAlign:"center",background:T.raised}}><div style={{fontSize:36,marginBottom:6}}>{"\uD83D\uDD75\uFE0F"}</div><div style={{fontSize:18,fontWeight:800,color:T.tx}}>{t("tbTitle")}</div><div style={{fontSize:12,color:T.sub,marginTop:2}}>{t("tb46")}</div></div>
      <div style={{...C,padding:"18px 20px",marginBottom:16}}>
        <input value={myName} onChange={e=>sMyN(e.target.value)} placeholder={t("name")} maxLength={12} style={{width:"100%",background:"transparent",border:"none",borderBottom:`2px solid ${myName?A.ro:T.ln}`,padding:"10px 0",color:T.tx,fontSize:18,fontWeight:800,outline:"none",fontFamily:"inherit",textAlign:"center"}}/>
        <div style={{fontSize:10,color:T.mt,letterSpacing:2,textTransform:"uppercase",textAlign:"center",marginTop:16,marginBottom:10}}>{t("avatar")}</div>
        <div style={{display:"grid",gridTemplateColumns:"repeat(5,1fr)",gap:8}}>{AVATARS.map(a=><button key={a} onClick={()=>{sfx.tap();sMyA(a);}} style={{width:"100%",aspectRatio:"1",borderRadius:12,background:myAv===a?`${A.ro}30`:T.raised,border:myAv===a?`2px solid ${A.ro}`:`1px solid ${T.ln}`,fontSize:24,cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center"}}>{a}</button>)}</div>
      </div>
      <div style={{display:"flex",gap:14,justifyContent:"center"}}>
        <div style={{textAlign:"center"}}><button onClick={()=>{if(!myName.trim())return;sfx.tap();H.l();sCode(genCode());sLobby([{name:myName.trim(),avatar:myAv,host:true}]);sStep("lobby");}} disabled={!myName.trim()} style={{width:80,height:80,borderRadius:"50%",border:"none",cursor:myName.trim()?"pointer":"default",background:myName.trim()?GR.trust:T.raised,fontSize:28,color:"#fff",display:"flex",alignItems:"center",justifyContent:"center",boxShadow:myName.trim()?GL(A.ro,14):"none",opacity:myName.trim()?1:.3}}>+</button><div style={{fontSize:12,color:T.sub,marginTop:6,fontWeight:600}}>{t("create")}</div></div>
        <div style={{textAlign:"center"}}><button onClick={()=>{if(!myName.trim())return;sfx.tap();H.l();sStep("joinCode");}} disabled={!myName.trim()} style={{width:80,height:80,borderRadius:"50%",border:"none",cursor:myName.trim()?"pointer":"default",background:myName.trim()?`linear-gradient(135deg,${A.sk},${A.cy})`:T.raised,fontSize:28,color:"#fff",display:"flex",alignItems:"center",justifyContent:"center",boxShadow:myName.trim()?GL(A.sk,14):"none",opacity:myName.trim()?1:.3}}>{"\u2192"}</button><div style={{fontSize:12,color:T.sub,marginTop:6,fontWeight:600}}>{t("join")}</div></div>
      </div>
    </div>}

    {step==="joinCode"&&<div style={{animation:"up .4s ease",textAlign:"center"}}>
      <div style={{fontSize:36,marginBottom:8}}>{"\uD83D\uDD11"}</div>
      <div style={{fontSize:18,fontWeight:800,color:T.tx,marginBottom:14}}>{t("joinRoom")}</div>
      <input value={code} onChange={e=>sCode(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,6))} placeholder="CODE" maxLength={6} style={{width:"100%",maxWidth:260,background:T.raised,border:`2px solid ${code.length===6?A.ro:T.ln}`,borderRadius:14,padding:"16px",color:T.tx,fontSize:26,fontWeight:900,fontFamily:"monospace",outline:"none",textAlign:"center",letterSpacing:8}}/>
      <div style={{marginTop:16}}><Btn primary onClick={()=>{if(code.length<6)return;sfx.tap();sLobby([{name:"Host",avatar:"\uD83D\uDE0E",host:true},{name:myName.trim(),avatar:myAv,host:false}]);sStep("lobby");}} disabled={code.length<6}>{t("join")}</Btn></div>
    </div>}

    {step==="lobby"&&<div style={{animation:"up .4s ease",textAlign:"center"}}>
      <button onClick={copyCode} style={{...C,display:"inline-block",padding:"12px 28px",marginBottom:16,background:T.raised,cursor:"pointer",fontFamily:"inherit"}}><div style={{fontSize:9,color:T.mt,letterSpacing:2,textTransform:"uppercase"}}>{t("roomCode")}</div><div style={{fontSize:34,fontWeight:900,color:A.ro,fontFamily:"monospace",letterSpacing:8}}>{code}</div><div style={{fontSize:10,color:A.v,marginTop:2}}>{"\uD83D\uDCCB"} {t("shareCode")}</div></button>
      <div style={{...C,padding:14,marginBottom:14,textAlign:"left"}}>
        <div style={{fontSize:10,color:T.mt,letterSpacing:2,textTransform:"uppercase",marginBottom:10}}>{t("players")} ({lobby.length}/6)</div>
        {lobby.map((p,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:10,padding:"10px 0",borderBottom:i<lobby.length-1?`1px solid ${T.ln}`:"none"}}><div style={{fontSize:24}}>{p.avatar}</div><div style={{flex:1}}><span style={{fontWeight:700,fontSize:14,color:T.tx}}>{p.name}</span>{p.host&&<span style={{fontSize:9,color:A.ro,marginLeft:6,fontWeight:700,background:`${A.ro}20`,padding:"2px 6px",borderRadius:4}}>HOST</span>}</div>{!p.host&&<button onClick={()=>sLobby(l=>l.filter((_,j)=>j!==i))} style={{background:"none",border:"none",color:A.ro,cursor:"pointer",fontSize:14}}>{"\u2715"}</button>}</div>)}
      </div>
      {lobby.length<6&&<div style={{...C,padding:"12px 16px",marginBottom:14}}><div style={{display:"flex",gap:8,alignItems:"center"}}><input value={addName} onChange={e=>sAN(e.target.value)} placeholder={`${t("player")}...`} maxLength={12} onKeyDown={e=>{if(e.key==="Enter")addP();}} style={{flex:1,background:"transparent",border:"none",borderBottom:`2px solid ${addName?A.ro:T.ln}`,padding:"6px 0",color:T.tx,fontSize:14,fontWeight:700,outline:"none",fontFamily:"inherit",textAlign:"center"}}/><select value={addAv} onChange={e=>sAA(e.target.value)} style={{fontSize:22,background:"transparent",border:"none",cursor:"pointer"}}>{AVATARS.map(a=><option key={a} value={a}>{a}</option>)}</select><button onClick={addP} disabled={!addName.trim()} style={{width:36,height:36,borderRadius:10,background:addName.trim()?GR.trust:T.raised,border:"none",color:"#fff",fontSize:18,cursor:addName.trim()?"pointer":"default",opacity:addName.trim()?1:.3}}>+</button></div></div>}
      <div style={{display:"flex",alignItems:"center",justifyContent:"center",gap:10,marginBottom:14}}><span style={{fontSize:12,color:T.sub}}>{t("rnds")}:</span>{[3,4,5].map(r=><button key={r} onClick={()=>{sfx.tap();sTR(r);}} style={{width:38,height:38,borderRadius:10,border:"none",background:tRnd===r?GR.trust:T.raised,color:"#fff",fontWeight:800,fontSize:15,cursor:"pointer"}}>{r}</button>)}</div>
      <Btn primary onClick={startG} disabled={lobby.length<4} style={{width:"100%",maxWidth:300}}>{t("startGame")}</Btn>
    </div>}
    {step==="assigning"&&<div style={{textAlign:"center",padding:"60px 16px",animation:"fadeIn .4s ease"}}><div style={{fontSize:60,marginBottom:16,animation:"float 1s ease infinite"}}>{"\uD83C\uDFAD"}</div><div style={{fontSize:20,fontWeight:800,color:T.tx,marginBottom:12}}>{t("rolesDistr")}</div><div style={{display:"flex",gap:8,justifyContent:"center",marginBottom:16}}>{[0,1,2,3,4].map(i=><div key={i} style={{width:10,height:10,borderRadius:5,background:[A.ro,A.or,A.am,A.em,A.v][i],animation:`dotP 1.4s ease ${i*.15}s infinite`}}/>)}</div><div style={{fontSize:12,color:T.sub,fontStyle:"italic"}}>{t("whoFakeSab")}</div></div>}
    {step==="roleReveal"&&<div style={{textAlign:"center",padding:"30px 16px",animation:"pop .4s ease"}}><div style={{fontSize:13,color:T.sub,marginBottom:14}}>{t("passPhone")}</div><div style={{fontSize:26,fontWeight:900,background:GR.brand,WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent",marginBottom:16}}>{pl[rrI]?.n}</div>{!rrS?<button onClick={()=>{sfx.tap();H.m();sRRS(true);}} style={{...C,padding:"28px 32px",cursor:"pointer",fontFamily:"inherit",borderStyle:"dashed",display:"inline-block"}}><div style={{fontSize:14,color:T.sub}}>{t("tapSee")}</div></button>:<div style={{animation:"pop .3s ease"}}><div style={{...C,padding:"20px 24px",marginBottom:16,borderTop:`3px solid ${roles[rrI]==="fake"?A.or:roles[rrI]==="saboteur"?A.ro:A.em}`}}><div style={{fontSize:28,fontWeight:900,color:roles[rrI]==="fake"?A.or:roles[rrI]==="saboteur"?A.ro:A.em}}>{roles[rrI]==="fake"?`\uD83C\uDFAD ${t("fake")}`:roles[rrI]==="saboteur"?`\uD83D\uDDE1\uFE0F ${t("sab")}`:`\u2705 ${t("norm")}`}</div><div style={{fontSize:11,color:T.sub,marginTop:6}}>{roles[rrI]==="fake"?t("fakeD"):roles[rrI]==="saboteur"?t("sabD"):t("normD")}</div></div><div style={{fontSize:11,color:A.ro,marginBottom:12}}>{t("noShow")}</div><Btn primary onClick={nextRR}>{rrI<n-1?t("next"):t("start")+"!"}</Btn></div>}</div>}
    {step==="roundPre"&&<div style={{textAlign:"center",padding:"32px 16px",animation:"up .4s ease"}}><div style={{fontSize:10,color:T.mt,letterSpacing:3,textTransform:"uppercase",marginBottom:4}}>{t("rnd")} {rnd}/{tRnd}</div><div style={{fontSize:13,color:T.sub,marginBottom:12}}>{t("passPhone")}</div><div style={{fontSize:26,fontWeight:900,background:GR.brand,WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent",marginBottom:8}}>{pl[ci]?.n}</div><div style={{...C,display:"inline-block",padding:"10px 20px",borderLeft:`3px solid ${A.v}`,marginBottom:16}}><div style={{fontSize:9,color:T.mt,letterSpacing:2,textTransform:"uppercase"}}>{t("tgt")}</div><div style={{fontSize:30,fontWeight:900,color:T.tx,fontFamily:"monospace"}}>{tgt.toFixed(1)}s</div></div><br/><Btn primary onClick={()=>{sBs("ready");sStep("roundPlay");}}>{t("ready")}</Btn></div>}
    {step==="roundPlay"&&<div style={{animation:"up .3s ease"}}><div style={{textAlign:"center",marginBottom:10}}><span style={{fontSize:13,fontWeight:700,color:A.v}}>{pl[ci]?.n}</span></div><div style={{textAlign:"center",marginBottom:14}}><div style={{...C,display:"inline-block",padding:"8px 16px",borderLeft:`3px solid ${A.v}`}}><span style={{fontSize:9,color:T.mt}}>{t("tgt")}: </span><span style={{fontSize:20,fontWeight:900,color:T.tx,fontFamily:"monospace"}}>{tgt.toFixed(1)}s</span></div></div><Buzzer state={bs} onTap={tap}/></div>}
    {step==="hidden"&&<div style={{textAlign:"center",padding:"40px 16px",animation:"fadeIn .4s ease"}}>{hP==="loading"&&<div><div style={{display:"flex",gap:6,justifyContent:"center",marginBottom:8}}>{[0,1,2].map(i=><div key={i} style={{width:8,height:8,borderRadius:4,background:A.v,animation:`dotP 1.2s ease ${i*.2}s infinite`}}/>)}</div><div style={{fontSize:14,color:T.sub}}>{t("calc")}</div></div>}{hP==="fake"&&<div style={{animation:"pop .3s ease"}}><div style={{fontSize:13,color:T.sub,marginBottom:6}}>{t("giveTo")}</div><div style={{fontSize:22,fontWeight:800,color:A.or,marginBottom:4}}>{pl[fIdx]?.n}</div><div style={{fontSize:11,color:T.mt,marginBottom:4}}>{t("yourTimeWas")}: <span style={{color:T.tx,fontWeight:700,fontFamily:"monospace"}}>{raw[fIdx]?.toFixed(3)}s</span></div><div style={{display:"flex",gap:8,justifyContent:"center",marginTop:12}}><Btn onClick={()=>fakeAct("minus")} gradient={GR.cool} small>-0.4s</Btn><Btn onClick={fakeSkip} small>{t("skip")}</Btn><Btn onClick={()=>fakeAct("plus")} gradient={GR.warm} small>+0.4s</Btn></div></div>}{hP==="sab"&&<div style={{animation:"pop .3s ease"}}><div style={{fontSize:13,color:T.sub,marginBottom:6}}>{t("giveTo")}</div><div style={{fontSize:22,fontWeight:800,color:A.ro,marginBottom:4}}>{pl[sIdx]?.n}</div>{sU?<div><div style={{fontSize:12,color:T.mt,marginBottom:12}}>{t("alrUsed")}</div><Btn onClick={()=>{sHP("loading");setTimeout(()=>sHP("done"),1200);}} small>OK</Btn></div>:<div><div style={{fontSize:12,color:T.sub,marginBottom:10}}>{t("sabotage")}:</div><div style={{display:"flex",flexDirection:"column",gap:6}}>{pl.map((p,i)=>i!==sIdx&&<button key={i} onClick={()=>sabAct(i)} style={{...C,padding:"12px 16px",cursor:"pointer",fontFamily:"inherit",textAlign:"left"}}><span style={{color:T.tx,fontWeight:700,fontSize:13}}>{p.n}</span></button>)}<Btn onClick={sabSkip} small style={{marginTop:4}}>{t("skip")}</Btn></div></div>}</div>}{hP==="done"&&<div style={{display:"flex",gap:6,justifyContent:"center"}}>{[0,1,2].map(i=><div key={i} style={{width:8,height:8,borderRadius:4,background:A.em,animation:`dotP 1.2s ease ${i*.2}s infinite`}}/>)}</div>}</div>}
    {step==="roundResult"&&<div style={{maxWidth:380,margin:"0 auto",animation:"up .3s ease"}}><div style={{textAlign:"center",marginBottom:12}}><div style={{fontSize:10,color:T.mt,letterSpacing:3,textTransform:"uppercase"}}>{t("rnd")} {rnd}/{tRnd}</div></div>{curRes().map((r,i)=><div key={r.idx} style={{display:"flex",alignItems:"center",gap:9,...C,padding:"11px 14px",marginBottom:7,borderLeft:`3px solid ${stL(r.ms).c}`,animation:`sL .4s ease ${i*.08}s both`}}><div style={{fontSize:18,width:28,textAlign:"center"}}>{medal(r.rank)}</div><div style={{flex:1}}><div style={{fontWeight:700,fontSize:13,color:T.tx}}>{r.name}</div><div style={{fontSize:11,color:T.sub,fontFamily:"monospace"}}>{r.time.toFixed(3)}s</div></div><div style={{textAlign:"right"}}><div style={{fontFamily:"monospace",fontWeight:800,fontSize:13,color:stL(r.ms).c}}>{r.ms}ms</div><div style={{fontSize:9,color:stL(r.ms).c,fontWeight:600}}>{r.status}</div></div></div>)}<div style={{textAlign:"center",marginTop:6,fontSize:11,color:T.sub,fontStyle:"italic"}}>{t("discuss")}</div><div style={{textAlign:"center",marginTop:14}}><Btn primary onClick={nextRound}>{rnd>=tRnd?t("voting"):t("nextRnd")}</Btn></div></div>}
    {step==="vote"&&<div style={{textAlign:"center",padding:"16px",animation:"up .4s ease"}}><div style={{fontSize:13,color:T.sub,marginBottom:6}}>{t("giveTo")}</div><div style={{fontSize:22,fontWeight:800,background:GR.brand,WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent",marginBottom:14}}>{pl[vI]?.n}</div><div style={{fontSize:14,fontWeight:700,color:T.tx,marginBottom:8}}>{t("whoFake")}</div><div style={{display:"flex",gap:6,justifyContent:"center",flexWrap:"wrap",marginBottom:14}}>{pl.map((p,i)=>i!==vI&&<button key={i} onClick={()=>{sfx.tap();sVF(i);}} style={{...C,padding:"10px 16px",cursor:"pointer",fontFamily:"inherit",background:vF===i?`${A.or}20`:T.card,borderColor:vF===i?A.or:T.ln}}><span style={{color:vF===i?A.or:T.tx,fontWeight:700,fontSize:13}}>{p.n}</span></button>)}</div><div style={{fontSize:14,fontWeight:700,color:T.tx,marginBottom:8}}>{t("whoSab")}</div><div style={{display:"flex",gap:6,justifyContent:"center",flexWrap:"wrap",marginBottom:16}}>{pl.map((p,i)=>i!==vI&&<button key={i} onClick={()=>{sfx.tap();sVS(i);}} style={{...C,padding:"10px 16px",cursor:"pointer",fontFamily:"inherit",background:vS===i?`${A.ro}20`:T.card,borderColor:vS===i?A.ro:T.ln}}><span style={{color:vS===i?A.ro:T.tx,fontWeight:700,fontSize:13}}>{p.n}</span></button>)}</div><Btn primary onClick={subVote} disabled={vF===null||vS===null}>{vI<n-1?t("vote"):t("reveal")}</Btn></div>}
    {step==="reveal"&&<div style={{textAlign:"center",padding:"20px 12px",animation:"pop .5s ease"}}><Confetti/><div style={{fontSize:24,fontWeight:900,color:T.tx,marginBottom:14}}>{t("revealed")}</div>{pl.map((p,i)=>{const role=roles[i];const rc=role==="fake"?A.or:role==="saboteur"?A.ro:A.em;const vFk=Object.values(votes).filter(v=>v.fake===i).length;const vSb=Object.values(votes).filter(v=>v.sab===i).length;return <div key={i} style={{...C,padding:"14px 16px",marginBottom:8,borderLeft:`4px solid ${rc}`,textAlign:"left",animation:`sL .4s ease ${i*.1}s both`}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontWeight:800,fontSize:14,color:T.tx}}>{p.n}</span><span style={{fontWeight:800,fontSize:12,color:rc}}>{role==="fake"?`\uD83C\uDFAD ${t("fake")}`:role==="saboteur"?`\uD83D\uDDE1\uFE0F ${t("sab")}`:`\u2705 ${t("norm")}`}</span></div>{(vFk>0||vSb>0)&&<div style={{fontSize:10,color:T.sub,marginTop:4}}>{vFk>0&&<span style={{marginRight:8}}>{t("fake")}: {vFk}x</span>}{vSb>0&&<span>{t("sab")}: {vSb}x</span>}</div>}</div>;})}{(()=>{const fV=Object.values(votes).filter(v=>v.fake===fIdx).length;const sV2=Object.values(votes).filter(v=>v.sab===sIdx).length;const maj=Math.ceil(n/2);const nW=fV>=maj&&sV2>=maj;return <div style={{...C,padding:16,marginTop:12,textAlign:"center",borderTop:`3px solid ${nW?A.em:A.ro}`}}><div style={{fontSize:18,fontWeight:900,color:nW?A.em:A.ro,marginBottom:4}}>{nW?t("normWin"):t("cheatWin")}</div><div style={{fontSize:11,color:T.sub}}>{t("fake")} {fV>=maj?t("exposed"):t("undetected")} ({fV}/{maj}) · {t("sab")} {sV2>=maj?t("exposed"):t("undetected")} ({sV2}/{maj})</div></div>;})()}<div style={{display:"flex",gap:10,justifyContent:"center",marginTop:16}}><Btn primary onClick={onBack}>{t("home")}</Btn></div></div>}
  </div>;
}

/* ══════════════════════════════════════════
   SETTINGS
   ══════════════════════════════════════════ */
function Settings({onBack}){const{lang,theme,setLang,setTheme,t,T}=useApp();return <div style={{animation:"up .4s ease"}}><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:20}}><Btn onClick={onBack} small>{"\u2190"} {t("back")}</Btn></div><div style={{textAlign:"center",marginBottom:20}}><div style={{fontSize:22,fontWeight:900,color:T.tx}}>{t("settings")}</div></div><div style={{background:T.card,borderRadius:16,border:`1px solid ${T.ln}`,padding:16,marginBottom:14}}><div style={{fontSize:10,color:T.mt,letterSpacing:2,textTransform:"uppercase",marginBottom:10}}>{t("lang")}</div><div style={{display:"flex",gap:8}}>{[{id:"de",lb:"Deutsch",fl:"\uD83C\uDDE9\uD83C\uDDEA"},{id:"en",lb:"English",fl:"\uD83C\uDDEC\uD83C\uDDE7"},{id:"sq",lb:"Shqip",fl:"\uD83C\uDDE6\uD83C\uDDF1"}].map(l=><button key={l.id} onClick={()=>{sfx.tap();setLang(l.id);}} style={{flex:1,padding:"12px 8px",borderRadius:12,border:lang===l.id?`2px solid ${A.v}`:`1px solid ${T.ln}`,background:lang===l.id?`${A.v}20`:T.raised,cursor:"pointer",fontFamily:"inherit",textAlign:"center"}}><div style={{fontSize:22,marginBottom:4}}>{l.fl}</div><div style={{fontSize:11,fontWeight:700,color:lang===l.id?A.v:T.tx}}>{l.lb}</div></button>)}</div></div><div style={{background:T.card,borderRadius:16,border:`1px solid ${T.ln}`,padding:16}}><div style={{fontSize:10,color:T.mt,letterSpacing:2,textTransform:"uppercase",marginBottom:10}}>{t("theme")}</div><div style={{display:"flex",gap:8}}>{[{id:"dark",k:"dark",ic:"\uD83C\uDF19"},{id:"light",k:"light",ic:"\u2600\uFE0F"}].map(m=><button key={m.id} onClick={()=>{sfx.tap();setTheme(m.id);}} style={{flex:1,padding:"14px 12px",borderRadius:12,border:theme===m.id?`2px solid ${A.v}`:`1px solid ${T.ln}`,background:theme===m.id?`${A.v}20`:T.raised,cursor:"pointer",fontFamily:"inherit",textAlign:"center"}}><div style={{fontSize:24,marginBottom:4}}>{m.ic}</div><div style={{fontSize:12,fontWeight:700,color:theme===m.id?A.v:T.tx}}>{t(m.k)}</div></button>)}</div></div></div>;}

/* ══════════════════════════════════════════
   HOME
   ══════════════════════════════════════════ */
function Home({go}){const{t,T}=useApp();return <div style={{textAlign:"center",paddingTop:20,animation:"fadeIn .5s ease"}}><div style={{fontSize:50,animation:"float 3s ease infinite",marginBottom:4}}>{"\u23F1\uFE0F"}</div><h1 style={{fontSize:42,fontWeight:900,margin:"0 0 4px",background:GR.brand,WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent",lineHeight:1.1}}>TimeTap</h1><p style={{color:T.sub,fontSize:14,marginBottom:24}}>{t("sub")}</p><div style={{maxWidth:360,margin:"0 auto",display:"flex",flexDirection:"column",gap:12}}>{[{k:"solo",ic:"\uD83C\uDFAF",tk:"solo",dk:"soloD",gr:GR.cool,cl:A.v},{k:"multi",ic:"\uD83C\uDFB2",tk:"multi",dk:"multiD",gr:GR.brand,cl:A.pk},{k:"tb",ic:"\uD83D\uDD75\uFE0F",tk:"tb",dk:"tbD",gr:GR.trust,cl:A.ro}].map((m,i)=><button key={m.k} onClick={()=>{sfx.tap();H.l();go(m.k);}} style={{background:T.card,borderRadius:16,border:`1px solid ${T.ln}`,padding:0,overflow:"hidden",cursor:"pointer",textAlign:"left",fontFamily:"inherit",transition:"transform .2s",animation:`sL .4s ease ${i*.07}s both`,boxShadow:GL(m.cl)}} onMouseEnter={e=>e.currentTarget.style.transform="translateY(-2px)"} onMouseLeave={e=>e.currentTarget.style.transform="translateY(0)"}><div style={{background:m.gr,padding:"18px 20px",display:"flex",alignItems:"center",gap:14}}><div style={{fontSize:28}}>{m.ic}</div><div><div style={{fontSize:18,fontWeight:800,color:"#fff"}}>{t(m.tk)}</div><div style={{fontSize:11,color:"rgba(255,255,255,.7)"}}>{t(m.dk)}</div></div></div></button>)}</div><button onClick={()=>{sfx.tap();go("settings");}} style={{marginTop:20,background:T.raised,border:`1px solid ${T.ln}`,borderRadius:12,padding:"10px 20px",cursor:"pointer",fontFamily:"inherit",display:"inline-flex",alignItems:"center",gap:8}}><span style={{fontSize:16}}>{"\u2699\uFE0F"}</span><span style={{fontSize:13,fontWeight:600,color:T.sub}}>{t("settings")}</span></button><div style={{marginTop:16,color:T.mt,fontSize:10}}>TimeTap v5.1</div></div>;}

/* ══════════════════════════════════════════
   APP
   ══════════════════════════════════════════ */
export default function App(){const[s,sS]=useState("home");const[lang,setLang]=useState("de");const[theme,setTheme]=useState("dark");const T=TH[theme];const t2=(k)=>L[lang]?.[k]||L.de[k]||k;
  useEffect(()=>{const el=document.createElement("style");el.textContent=CSS;document.head.appendChild(el);return()=>document.head.removeChild(el);},[]);
  const home=()=>sS("home");const ctx={lang,theme,setLang,setTheme,T,t:t2};
  return <Ctx.Provider value={ctx}><div style={{minHeight:"100vh",background:T.bg,fontFamily:"'SF Pro Display','Segoe UI',system-ui,sans-serif",color:T.tx,padding:"12px 14px 32px",maxWidth:440,margin:"0 auto",transition:"background .3s,color .3s"}}>{s==="home"&&<Home go={sS}/>}{s==="solo"&&<Solo onBack={home}/>}{s==="multi"&&<MultiHub onBack={home}/>}{s==="tb"&&<TrustBreaker onBack={home}/>}{s==="settings"&&<Settings onBack={home}/>}</div></Ctx.Provider>;}
